### PR TITLE
Fix #2839: 'continuous_scale' palette param docs

### LINKED ISSUE #2839: Documentation of `palette` parameter for continuous scales
The documentation is incorrect:

```
continuous_scale            package:ggplot2            R Documentation

Continuous scale constructor.

Description:

     Continuous scale constructor.

Usage:

     continuous_scale(aesthetics, scale_name, palette, name = waiver(),
       breaks = waiver(), minor_breaks = waiver(), labels = waiver(),
       limits = NULL, rescaler = rescale, oob = censor, expand = waiver(),
       na.value = NA_real_, trans = "identity", guide = "legend",
       position = "left", super = ScaleContinuous)
     
Arguments:

aesthetics: The names of the aesthetics that this scale works with

scale_name: The name of the scale

 palette: A palette function that when called with a single integer
          argument (the number of levels in the scale) returns the
          values that they should take
```

This is the expected behavior of `palette` for `discrete_scale`.  Currently `continuous_scale` and `discrete_scale` share the same documentation for this parameter.  PR coming shortly.

### PR DESCRIPTION
**Pull request by brodieG**
The 'palette' parameter has different usage in continuous
vs discrete scales, and the documentation described the
discrete usage.

### CODE REVIEW

**Comment by hadley** [comment]
Could you please re-roxygenise?

**Comment by clauswilke** [comment]
Out-of-date .Rds should be fixed since #2833.

**Comment by brodieG** [comment]
Should be ready for review now.  There were still a few other unrendered mds that I left out of this PR.

**Comment by clauswilke** [comment]
Thanks!

**Pull request merged**
