### PR TITLE
Type argument in scale_[fill/colour]_[continuous/binned] can accept a function

### PR DESCRIPTION
**Pull request by cpsievert**
See #3827

### CODE REVIEW

**Comment by hadley** [comment]
This seems reasonable to me.

**Comment by thomasp85** [comment]
@cpsievert can you add a small note in NEWS.md?

**Comment by cpsievert** [comment]
@thomasp85 good to merge? Those build failures look like false positives

**Comment by thomasp85** [comment]
Thanks!

**Pull request merged**
