### PR TITLE
Fixed typo in discrete_scales doc

### PR DESCRIPTION
**Pull request by burchill**
I'm assuming this is what the author meant to say?

It was originally (bold added):

> If `na.translate = TRUE`, **what value aesthetic value should missing be** displayed as? Does not apply to position scales where NA is always placed at the far right.

Now it is:

> If `na.translate = TRUE`, **what aesthetic value should the missing values be** displayed as? Does not apply to position scales where NA is always placed at the far right.

### CODE REVIEW

**Comment by yutannihilation** [comment]
Sounds good. Could you resolve the conflict? It seems you created a branch from a bit outdated master.

**Comment by burchill** [comment]
Alright, I have no idea why I can't seem to access the most recent version of master, even after doing ` git pull origin master`. 
I'm just going to delete my entire repo and start again, is that ok?

**Comment by yutannihilation** [comment]
Yeah, I'm fine if it's easier for you to delete the repo and create a new pull request.

> `git pull origin master`

My guess is that your `origin` is your repository, which has a separate `master` and it doesn't automatically follow `tidyverse/ggplot2`'s `master`. You typically need to add `tidyverse/ggplot2` to `remote` with some name like `upstream` and do `git pull upstream master` on your local master. Sorry, I can't find a handy git guide about this, but hope this helps you a bit next time!

**Comment by burchill** [comment]
Fixed this by redoing everything in #3970 . Closing this PR

**Pull request closed without merging**
