### PR TITLE
Fix Position docs

### PR DESCRIPTION
**Pull request by flying-sheep**
The function signature is `compute_panel(self, data, params, scales) -> data`

### CODE REVIEW

**Comment by thomasp85** [comment]
Thanks

**Comment by yutannihilation** [comment]
FYI: you needed to run `devtools::document()` to re-generated the docs.

**Comment by flying-sheep** [comment]
Sure, but for one-off fixes using the GitHub UI, that’s not feasible.

Maybe there should be a bot that recognizes PRs that change `#' doc comments` where no `.Rd` changes happened and adds them in commits to (or after) that PR.

**Comment by batpigandme** [comment]
Given that there can be several functions inside a single `.R` file that export to different `.Rd`s, and roxygen's parsing of tags, this would be non-trivial. I'm not sure where a Feature Request for something like this world go. Maintainers with write access can always document for you, if it's a problem.

**Comment by flying-sheep** [comment]
The idea is simpler: If any line in a `.R` file starting with `#'` is changed, but no file with an `.Rd` extension is changed in the same PR, the bot checks out the changes, runs `devtools::document()` and checks if that would produce any changes. If it does, it either commits them directly to the existing PR or creates another PR depending on it.

**Comment by batpigandme** [comment]
I like the idea. It deserves to live somewhere other than ggplot2 PR comments.

**Comment by flying-sheep** [comment]
What are you thinking? Sadly roxygen2 doesn’t live in an organization where we could propose that.

**Comment by hadley** [comment]
It's already in the pipeline.

**Pull request merged**
