### PR TITLE
Add tests for values, limits, and breaks in manual scale

### LINKED ISSUE #4511: Error when combining scale_color_manual and guide_legend (override.aes) in v3.3.4
With the reprex below, I got the following error when changing the `alpha` and `size` values using `guide_legend (override.aes)`. Note that the current CRAN version (v3.3.3) worked without any error.

```
Error in `[[<-.data.frame`(`*tmp*`, i, value = c(0.6, 0.6)) : 
  replacement has 2 rows, data has 3
```

Reprex (data taken from this [issue](https://github.com/tidyverse/ggplot2/issues/4479))

``` r
library(ggplot2)
packageVersion("ggplot2")
#> [1] '3.3.3.9000'

groups <- LETTERS[1:3]

df <- data.frame(
  x = rep(1:10, 3),
  y = rnorm(30),
  group = rep(groups, each = 10)
)

```
Set up manual color scale

```r
my_color <- setNames(c("blue", "green", "red"), unique(df$group))
my_color
#>       A       B       C 
#>  "blue" "green"   "red"
```

Filter out group "A"

```r

df1 <- df[df$group != "A", ]
df1
#>     x             y group
#> 11  1  0.7970884438     B
#> 12  2  1.0696606257     B
#> 13  3 -0.4524050451     B
#> 14  4  0.1683655197     B
#> 15  5  0.0723548494     B
#> 16  6  0.2621733369     B
#> 17  7 -0.6167289461     B
#> 18  8  0.3669677647     B
#> 19  9 -0.6197559708     B
#> 20 10 -0.6741798000     B
#> 21  1 -0.9238588784     C
#> 22  2  1.0908007314     C
#> 23  3 -0.8173714908     C
#> 24  4  0.3555677658     C
#> 25  5  0.0862835605     C
#> 26  6 -0.1650330989     C
#> 27  7 -0.6288903181     C
#> 28  8 -0.2195618380     C
#> 29  9  1.1759632572     C
#> 30 10  0.0005726088     C
```

```r
n_group <- length(unique(df1$group))
n_group
#> [1] 2

p1 <- ggplot(df1, aes(x, y, colour = group)) +
  geom_point(size = 3)
p1
```

Legend for group "A" shows up even though we don't have it anymore (this wasn't the problem with v3.3.3 CRAN)

``` r
p1 +
  scale_colour_manual(
    "",
    values = my_color
  )
```

``` r
p1 +
  scale_colour_manual(
    "",
    values = my_color
  ) +
  guides(color = guide_legend(title = "",
                              override.aes = list(alpha  = rep(0.6, n_group),
                                                  size   = rep(6,   n_group)),
                              order = 1),
         stroke = "none",
         shape  = "none")
#> Error in `[[<-.data.frame`(`*tmp*`, i, value = c(0.6, 0.6)): replacement has 2 rows, data has 3
```

<sup>Created on 2021-06-14 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

### LINKED ISSUE #4534: values vector in scale_color_manual
The behavior of `scale_color_manual(values = ...)` seems to have changed recently and broke many of my plots. 

Consider this example:

```R
suppressPackageStartupMessages({
  library(ggplot2)
  library(dplyr)
})

color_map <- list(r = "red", g = "green", b = "blue")

randu %>%
  mutate(color_key = as.factor(if_else(x > y, "r", "g"))) %>%
  ggplot(aes(x = x, y = y, fill = color_key)) + 
  scale_fill_manual(values = color_map) +
  geom_point(shape = 21, size = 7)
```

It now produces a figure with the blue color _also_ in the legend. 
I find that the following works (blue does not appear in the legend):

```R
randu %>%
  mutate(color_key = as.factor(if_else(x > y, "r", "g"))) %>%
  {
    ggplot(., aes(x = x, y = y, fill = color_key)) + 
      scale_fill_manual(values = color_map, breaks = .$col) +
      # scale_fill_manual(values = color_map[.$col]) +  # Alternative
      geom_point(shape = 21, size = 7)
  }
```

But this code looks unhappy. Is there a more robust way, in particular without extra temporary variables?

Is there somethin like `breaks = .df$fill`? This would be useful in many contexts.

Sidenote. This would make more sense to me:
```R
scale_fill_manual(values = color_map)  # no blue in the legend
scale_fill_manual(values = color_map, breaks = names(color_map))  # with blue in the legend
```

==

For lols, this works, too:

```R
gglast <- function(what) {
  p <- ggplot2::last_plot()
  q <- p$mapping[[deparse(substitute(what))]]
  rlang::eval_tidy(q, data = p$data)
}

randu %>%
  mutate(color_key = as.factor(if_else(x > y, "r", "g"))) %>%
  ggplot(aes(x = x, y = y, fill = color_key)) + 
  scale_fill_manual(values = color_map, breaks = gglast(fill)) +
  geom_point(shape = 21, size = 7)
```

### PR DESCRIPTION
**Pull request by banfai**
Issue introduced in #4471, if there are extra named values in a manual scale then they will show up on the legend even with `drop = TRUE`.

Question: should these values be forced with `drop = FALSE`? (currently it's possible)

### CODE REVIEW

**Comment by msberends** [comment]
> Question: should these values be forced with `drop = FALSE`? (currently it's possible)

I would very much like so. Probably a nice option to add legend items not present in the data if the plot is part of a series, or e.g. to make it obvious that a `factor` contains levels that have zero observations.

**Comment by yutannihilation** [comment]
@banfai 
Hi, thank you for creating this pull request. Recently, we got an alternative pull request (#4619) that tackles the same issue. We are getting to feel #4619 is preferred in that the change is only on manual scale, while your pull request modifies the whole `Scale`.

Would you mind tweaking this pull request to contain only the tests? These are helpful to check if #4619 does the right thing, and, what's more important, I'd like to make it clear that you are a contributor by merging this. The CI checks will of course fail, but it's fine. If you don't have time, I can do it.

**Comment by banfai** [comment]
Hi @yutannihilation @teunbrand 

Thanks for having a look at this. I have seen @teunbrand 's comment earlier on 4511 and agreed that it was a leaner solution, but haven't had time to look deeper or change this PR.
I have removed the changes in this and added some more tests. These pass on my computer with #4619 included.

**Review by yutannihilation — APPROVED** [review]

**Comment by yutannihilation** [comment]
Thank you!

**Pull request merged**
