### PR TITLE
fix a typo in NEWS.md

### PR DESCRIPTION
**Pull request by yutannihilation**

### CODE REVIEW

**Comment by yutannihilation** [comment]
Yeah, I too felt the phase mysterious, but I found what a "short" label is in `?quo_label()`:

``` r
# quo_name() is helpful when you need really short labels:
quo_name(quo(sym))
#> [1] "sym"
quo_name(quo(!! sym))
#> [1] "function (x) ..."
```

I'm still not sure about the actual use cases, but maybe this is useful when you create a label by deparsing an aes that is not a simple symbol and contains unquoted functions in its expression?

**Comment by clauswilke** [comment]
I think talking about "short" symbols is misleading:
```{r}
quo_name(quo(this_is_a_really_long_symbol_and_quo_name_has_no_problem_with_it))
#> [1] "this_is_a_really_long_symbol_and_quo_name_has_no_problem_with_it"
quo_text(quo(this_is_a_really_long_symbol_and_quo_name_has_no_problem_with_it))
#> [1] "this_is_a_really_long_symbol_and_quo_name_has_no_problem_with_it"
```
`quo_name()` and `quo_text()` seem to return the same result for symbols but different results for expressions. For expressions, at some point `quo_name()` starts to abbreviate but `quo_text()` keeps going:
```{r}
quo_name(quo(a + b + c + d + e + f + g + h + i + j + k + l + m + n + o + p))
#> [1] "a + b + c + d + e + f + g + h + i + j + k + l + m + n + o + p"
quo_name(quo(a + b + c + d + e + f + g + h + i + j + k + l + m + n + o + p + q))
#> [1] "+..."
quo_text(quo(a + b + c + d + e + f + g + h + i + j + k + l + m + n + o + p + q))
#> [1] "a + b + c + d + e + f + g + h + i + j + k + l + m + n + o + p + \n    q"
```

**Comment by hadley** [comment]
Yeah, it's long expressions that are shortened, not long symbols. We need to document this better in rlang; I think it's ok if it's slightly bewildering in the NEWS file — at least it gets people looking in the right direction (although better wording is, of course, appreciated)

**Comment by clauswilke** [comment]
How about:

> use `quo_name()` (to generate single-line strings; longer expressions may be abbreviated) or `quo_text()` (to generate non-abbreviated strings that may span multiple lines)

**Comment by hadley** [comment]
:+1:

**Comment by yutannihilation** [comment]
@clauswilke Thanks for the nice sentence! Should I include this? If you will create another PR, I'll close this here.

**Comment by clauswilke** [comment]
Yes, just include it in your PR. Thanks!

**Comment by yutannihilation** [comment]
Sure!

**Comment by yutannihilation** [comment]
Done.

**Comment by hadley** [comment]
Thanks!

**Pull request merged**
