### PR TITLE
Update vdiffr cases for sf 0.9-7 and fix forbidden "brew cask"

### PR DESCRIPTION
**Pull request by yutannihilation**
It seems sf 0.9-7 (published on CRAN yesterday) introduced a small change on axis labels. This pull request is to update the cases.

### Before
before

### After
after

---
edit: This pull request also fixes the following error on macOS runner due to the recent change on Homebrew

```
Error: Calling brew cask install is disabled! Use brew install [--cask] instead.
Error: Process completed with exit code 1.
```

### CODE REVIEW

**Comment by yutannihilation** [comment]
macOS runner will keep failing until the binary is built on CRAN. We might need to wait for a while.

**Comment by yutannihilation** [comment]
Hmm, OK, this error on macOS runner is another thing we need to fix.

```
Error: Calling brew cask install is disabled! Use brew install [--cask] instead.
Error: Process completed with exit code 1.
```

**Review by clauswilke — APPROVED** [review]
LGTM if the checks pass.

**Comment by yutannihilation** [comment]
Thanks!

**Comment by yutannihilation** [comment]
Ah, "brew cask" issue was already fixed on master yesterday.

https://github.com/tidyverse/ggplot2/commit/2389828a3527c478ade3117fc2b9c4755215613d

**Pull request merged**
