### PR TITLE
Partial polar plots

### PR DESCRIPTION
**Pull request by teunbrand**
This is my take on #4462, that adds an `end` argument to `coord_polar()` to allow partial polar plots.

In brief:

* There are no visual changes if `end` is not used.
* It was straightforward to rescale to [start, end] instead of [0, 2&pi;] to get the partial polar coordinates.
* After that rescaling, I had to account for the bounding box of the circle sector.
* The bit I found more difficult were the radius axis placement. I've resolved this as detailed below.

Normally, the axis is placed in the upper part of the y-axis. If we have only the lower part of a circle, I had to reflect the break positions:

``` r
devtools::load_all("~/packages/ggplot2/")
#> ℹ Loading ggplot2

p <- ggplot(mpg, aes(displ, hwy, colour = factor(cyl))) +
  geom_point()

p + coord_polar(start = 0.5 * pi, end = 1.5 * pi)
```

If 0 or &pi; are not in the [start, end] interval, I have placed the axis in the x-direction. (Below also reflected because left instead of right).

``` r
p + coord_polar(start = 1.25 * pi, end = 1.75 * pi)
```

If no integer multiple of 0.5&pi; is in that interval, I can't appropriately place an axis anywhere. In that case, I've thrown a message with instructions.

``` r
p + coord_polar(start = 0.1 * pi, end = 0.4 * pi)
#> Could not find appropriate placement for the radius axis.
#> ℹ A radius axis requires the [`start`-`end`] range to include one of: `c(0,
#>   0.5, 1, 1.5) * pi`.
```

<sup>Created on 2022-11-03 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

After the guides are ported over to the ggproto system, we might consider a more complete solution for axis placement than this.

### CODE REVIEW

**Comment by thomasp85** [comment]
Is this still meaningful to get in or should we tackle it from anew after ggproto guides have been merged?

**Comment by teunbrand** [comment]
I think the new ggproto guides don't interact with `coord_polar()` other than making `coord_polar()` skip doing proper guide stuff (as it wasn't using this), so these changes can safely co-exist. After the ggproto guides are merged, we can tackle bringing `coord_polar()` into the fold of guide-using coords, either in this PR or a new one. However, I'm pretty keen on the functionality that this PR adds.

**Comment by thomasp85** [comment]
ok, I'll do a review next week

**Comment by teunbrand** [comment]
Closing this PR in favour of #5334.

**Pull request closed without merging**
