### PR TITLE
Issue 2776 updated stat_ellipse documentation.

### PR DESCRIPTION
**Pull request by llendway**
Changed documentation to reflect computing data ellipses rather than confidence ellipses. Fixes documentation portion of issue #2776

### CODE REVIEW

**Comment by thomasp85** [comment]
You are correct in that it is derived from `dataEllipse()` and not `ellipse()`, but I fear the title change will confuse users... Is data ellipses a well understood description?  cc @hadley

**Comment by clauswilke** [comment]
I think the documentation needs a few sentences explaining what a data ellipse is/what this function does.

**Comment by hadley** [comment]
I think the proposed title is confusing too. These draw confidence ellipses computed from data.

**Comment by leonardblaschek** [comment]
> These draw confidence ellipses computed from data.

The trouble is that confidence ellipses are a rather tightly defined construct, and stat_ellipse does _not_ compute those. It computes data ellipses.

I agree that data ellipses are a somewhat obscure concept, and I too had to look it up when I stumbled over it (#2776). But I think keeping a misleading documentation just to not confuse people is a much worse idea. I regularly see high profile publications whose authors plot their PCAs in ggplot and annotate the data ellipses from stat_ellipse() as confidence ellipses, which is incorrect and misleading for everybody involved.

Ideally the underlying code of stat_ellipse() would be fixed, but for now this small change in documentation could prevent a lot of serious headaches.

**Comment by clauswilke** [comment]
Closing this as a similar PR (#3410) was merged recently.

**Pull request closed without merging**
