### PR TITLE
avoid replication of aesthetics across hex bins

### LINKED ISSUE #5037: hexbin is broken
It looks like since at least the latest release (3.4.0) `geom_hex` is broken in some way. For an example, see [the documentation](https://ggplot2.tidyverse.org/reference/geom_hex.html#ref-examples):

image

(Current state on left, expected output on the right.)

### LINKED ISSUE #5044: geom_hex color representation is wrong
Density/count data is correctly plotted with `geom_bin_2d()` or with manual counts via `geom_raster()`, but colors representing the counts are regularly off in `geom_hex()`.

It was working in a previous version (I apologize as I'm not sure exactly which version but around 2022-08-01)

Previous example, working as intended:

</img>

---

Reprex below - note the color difference in the `hex` - not quite reversed, but regularly wrong.

``` r
library(tidyverse)
library(patchwork)

souce_url <- "https://raw.githubusercontent.com/ArrowheadAnalytics/next-gen-scrapy-2.0/master/pass_and_game_data.csv"

pass_map_df <- read_csv(souce_url) %>%
  na.omit()

manual_raster <- pass_map_df |> 
  select(x, y) |> 
  mutate(x = round(x),
         y = round(y)) |> 
  group_by(x,y) |> 
  count() |> 
  ggplot(aes(x =x, y = y, fill = n)) +
  geom_raster() +
  scale_fill_gradient(low = "red", high = "yellow") +
  geom_hline(yintercept = c(2, 7), color = "grey") +
  scale_y_continuous(breaks = seq(-10, 60, 5)) +
  labs(title = "Manual calc raster")

bin2d <- pass_map_df %>%
  ggplot(aes(x = x, y = y)) +
  geom_bin_2d(
    binwidth = c(1, 1)
  ) +
  scale_fill_gradient(low = "red", high = "yellow") +
  geom_hline(yintercept = c(2, 7), color = "grey") +
  scale_y_continuous(breaks = seq(-10, 60, 5)) +
  labs(title = "Using bin2d")


hex_plot <- pass_map_df %>%
  ggplot(aes(x = x, y = y)) +
  geom_hex(
    binwidth = c(1, 1)
  ) +
  scale_fill_gradient(low = "red", high = "yellow") +
  geom_hline(yintercept = c(2, 7), color = "grey") +
  scale_y_continuous(breaks = seq(-10, 60, 5))

bin2d + manual_raster + hex_plot +
  plot_layout(ncol = 2, nrow = 2, heights = 1)+
  labs(title = "Using geom_hex")
```

<sup>Created on 2022-11-10 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

# Session Info

```
─ Session info ───────────────────────────────────────────────────────────────
 setting  value
 version  R version 4.2.0 (2022-04-22)
 os       macOS Monterey 12.6
 system   aarch64, darwin20
 ui       X11
 language (EN)
 collate  en_US.UTF-8
 ctype    en_US.UTF-8
 tz       America/Chicago
 date     2022-11-10
 pandoc   2.19.2 @ /Applications/RStudio.app/Contents/Resources/app/quarto/bin/tools/ (via rmarkdown)
 quarto   1.2.242 @ /usr/local/bin/quarto

─ Packages ───────────────────────────────────────────────────────────────────
 package     * version    date (UTC) lib source
 dplyr       * 1.0.10     2022-09-01 [1] CRAN (R 4.2.0)
 forcats     * 0.5.1      2021-01-27 [1] CRAN (R 4.2.0)
 ggExtra     * 0.10.0     2022-03-23 [1] CRAN (R 4.2.0)
 ggplot2     * 3.4.0      2022-11-04 [1] CRAN (R 4.2.0)
 ggridges    * 0.5.3      2021-01-08 [1] CRAN (R 4.2.0)
 ggtext      * 0.1.1      2022-09-14 [1] Github (wilkelab/ggtext@50fdaba)
 lubridate   * 1.8.0      2021-10-07 [1] CRAN (R 4.2.0)
 paletteer   * 1.5.0      2022-10-19 [1] CRAN (R 4.2.0)
 patchwork   * 1.1.0.9000 2022-04-26 [1] Github (thomasp85/patchwork@79223d3)
 purrr       * 0.3.5      2022-10-06 [1] CRAN (R 4.2.0)
 readr       * 2.1.3      2022-10-01 [1] CRAN (R 4.2.0)
 scales      * 1.2.1      2022-08-20 [1] CRAN (R 4.2.0)
 sessioninfo * 1.2.2      2021-12-06 [1] CRAN (R 4.2.0)
 stringr     * 1.4.1      2022-08-20 [1] CRAN (R 4.2.0)
 tibble      * 3.1.8      2022-07-22 [1] CRAN (R 4.2.0)
 tidyr       * 1.2.1      2022-09-08 [1] CRAN (R 4.2.0)
 tidyverse   * 1.3.2.9000 2022-08-16 [1] Github (tidyverse/tidyverse@3be8283)

 [1] /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library
```

### PR DESCRIPTION
**Pull request by thomasp85**
Fix #5037 and Fix #5044

This fixes a regression in the hex bin update in 3.4.0

### CODE REVIEW

**Comment by yutannihilation** [comment]
Thanks for addressing this. Could you describe what was the problem and what the fix is? As I wrote on https://github.com/tidyverse/ggplot2/issues/5037#issuecomment-1306485935, it seems [4e3f0e1](https://github.com/tidyverse/ggplot2/commit/4e3f0e1b25ad0efe68f8304576b543caadd156d1) was the first commit where `geom_hex()` is broken, and I don't understand why this fixes the problem (and what had gone wrong).

**Comment by thomasp85** [comment]
The issue was pretty dumb and benign... The coordinates for the hexes comes from replicating each input point six times and alter the values so it resembles a hexagon. During my update I took the gpar values from this replicated data.frame as well even though these should not be replicated. This lead to the fill replication reported. The unit tests will now guard against this

**Comment by yutannihilation** [comment]
Ah, I see. Thanks for the clear explanation! Then, this looks good to me.

**Review by yutannihilation — APPROVED** [review]

**Comment by yutannihilation** [comment]
@thomasp85 
May I merge this so that the users can easily check if their hexbin problem is fixed in the dev version?

**Comment by alekseybelikov** [comment]
I don't understand. What is the solution? I still have this problem with ggplot 3.4.0
Screenshot 2024-10-18 at 17 47 31

**Comment by wmoldham** [comment]
@alekseybelikov It looks like this was patched in 3.4.1. Try to upgrade to at least this version.

**Comment by alekseybelikov** [comment]
> @alekseybelikov It looks like this was patched in 3.4.1. Try to upgrade to at least this version.

Hi, unfortunately version 3.4.0 is specifically required for a scATACseq analysis tool ArchR to function: https://github.com/GreenleafLab/ArchR/issues/2130#issuecomment-2231419238

**Comment by alekseybelikov** [comment]
Ok, just upgraded to 3.4.1 and it solved the problem, but not sure if now new problems will arise in ArchR due to this.

```
ggplot_url <- "https://cran.r-project.org/src/contrib/Archive/ggplot2/ggplot2_3.4.0.tar.gz"
install.packages(ggplot_url, repos=NULL, type="source")
```
Screenshot 2024-10-18 at 18 36 29

**Comment by teunbrand** [comment]
Looks to me like ArchR was trying to grab a legend by name that has become outdated in `ArchR::fixPlotSize()`.
Once https://github.com/tidyverse/ggplot2/pull/6094 gets merged, they wouldn't have to resort to that fragile way of setting the plot size.

**Pull request merged**
