### PR TITLE
Refactor titleGrob() to eliminate the need for stripGrob()

### PR DESCRIPTION
**Pull request by karawoo**
As part of our overhaul of text placement, this PR:

* Splits `titleGrob()` into  `title_spec()` (which returns the text grob (and debugging grobs if requested), text height, and text width) and `add_margins()`, which should add the margins around the text grob but is clearly not working in strips, but does work for axis titles. `titleGrob()` now calls both `title_spec()` and `add_margins()`.
* Renames the `expand_x`/`expand_y` arguments to `margin_x`/`margin_y`.
* Removes `stripGrob()`. `build_strip()` and `ggstrip()` now call `title_spec()` and `add_margins()`.

``` r
df <- data.frame(
  x = 1:3,
  y = 1:3,
  z = c("a", "aaab", "aaaaaaabc"),
  g = c("b", "bbbb", "bbbbbbbcd")
)

base <- ggplot(df, aes(x, y)) + 
  geom_point() + 
  theme(strip.text.y = element_text(angle = 0))

base + facet_grid(g ~ z) +
  theme(
    strip.text.x = element_text(hjust = 0, debug = TRUE),
    strip.text.y = element_text(hjust = 0, debug = TRUE),
    axis.title.x = element_text(margin = margin(t = 30), debug = TRUE)
  )
```

### CODE REVIEW

**Comment by karawoo** [comment]
Arggh, this does not quite work. `facet_wrap`-ing by multiple variables is broken. 

```r
p1 <- ggplot(mtcars, aes(mpg, disp, colour = cyl)) +
  geom_point() +
  labs(title = "title of plot") +
  theme_test() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5)) +
  scale_x_continuous(breaks = mean(mtcars$mpg), labels = "very very long long axis label") +
  scale_y_continuous(breaks = mean(mtcars$disp), labels = "very very long long axis label")

p1 + facet_wrap(am~vs) + theme(legend.position = "right")
```

Before:

screen shot 2017-08-07 at 11 45 58 am

After:

screen shot 2017-08-07 at 11 46 10 am

Also the borders around strips are subtly changed. I will investigate.

**Comment by karawoo** [comment]
I don't know why the CI builds are passing, they should not be. I fixed the facet wrapping issue, the main thing that's left, besides adding a new visual test, is the strip borders. The y strips have thicker borders around the outside of the strips, but the x strips do not:

screen shot 2017-08-07 at 4 13 48 pm

**Comment by hadley** [comment]
The thicker border is most likely because something has changed in the plotting order and now the right strip is drawn on top of the plot (instead of beneath it). I'm not sure why our changes would have affected that - look for some interaction with ggtable.

**Comment by karawoo** [comment]
Something's still broken 😞 

``` r
df <- data.frame(
  x = 1,
  y = 1,
  z = c("aaaaaaabc"),
  g = c("bbbbbbbcd")
)

ggplot(df, aes(x, y)) + 
  facet_grid(g ~ z) +
  theme(strip.text.x = element_text(hjust = 0, debug = TRUE),
        strip.text.y = element_text(vjust = 0, debug = TRUE))
```

**Comment by karawoo** [comment]
Fixed the above issue; now both x and y strip text can be adjusted with `hjust` and won't run off the strip.

``` r
ggplot(df, aes(x, y)) + 
  facet_grid(g ~ z) +
  theme(strip.text.x = element_text(hjust = 0, debug = TRUE),
        strip.text.y = element_text(hjust = 1, debug = TRUE))
```

**Pull request merged**
