### PR TITLE
Set `width` as aesthetic in `geom_col()`/`geom_bar()`.

### LINKED ISSUE #3142: geom_bar()/geom_col() erroneously warn that they ignore width aesthetic
`geom_bar()` and `geom_col()` let you specify a `width` aesthetic to control the width of the bars.

The behavior is as expected, but it generates an erroneous warning "Warning: Ignoring unknown aesthetics: width".

`width` isn't listed in the aesthetics section of [`?geom_bar`](https://ggplot2.tidyverse.org/reference/geom_bar.html), so it appears that this is an unofficial behavior.

----

``` r
library(ggplot2)
suppressPackageStartupMessages(library(dplyr))
mtcars_by_cyl <- mtcars %>% 
  group_by(cyl) %>% 
  summarize(
    mean_wt = mean(wt),
    n = n()
  ) %>% 
  mutate(prop = n / sum(n))

ggplot(mtcars_by_cyl) + 
  geom_col(aes(cyl, mean_wt, width = prop))
#> Warning: Ignoring unknown aesthetics: width
```

Created on 2019-02-13 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

----

Similar closed issues.

- https://github.com/tidyverse/ggplot2/issues/1904
- https://github.com/tidyverse/ggplot2/issues/2473

### PR DESCRIPTION
**Pull request by teunbrand**
This PR aims to fix #3142.

Motivation is given here: https://github.com/tidyverse/ggplot2/issues/3142#issuecomment-2019903367. To recap: yes variable width bars are bad, but we allowed them implicitly anyway and are jumping through hoops to clunkily discourage it.
This PR removes  the hack that recognises `width` as a parameter, and implements it as an aesthetic instead.

### CODE REVIEW

**Review by thomasp85 — APPROVED** [review]
LGTM

**Comment by katossky** [comment]
Not sure whether I should comment here or on the issue :

- this feature seems to solve the `width` issue but not the `height` one
- more importantly, it does not work as I expect

```
# devtools::install_github("https://github.com/tidyverse/ggplot2")
ggplot2::diamonds |>
    dplyr::summarise(n=dplyr::n(), avgPrice=mean(price), .by=clarity) |>
    ggplot(aes(x=clarity, width=n, y=avgPrice)) +
    geom_col(fill=NA, color='black')
```

produces :

image

I checked that I have the correct version of `geom_bar` and indeed :

```
> geom_bar
function (mapping = NULL, data = NULL, stat = "count", position = "stack", 
    ..., just = 0.5, na.rm = FALSE, orientation = NA, show.legend = NA, 
    inherit.aes = TRUE) ...
```

... does not have the `width` parameter anymore.

**Comment by teunbrand** [comment]
> this feature seems to solve the width issue but not the height one

Can I ask what height issue exactly?

> more importantly, it does not work as I expect

Running that code with the CRAN version or even older versions such as 3.4.4 yields the same plot, so I'm reasonably sure that this PR didn't affect that outcome.

**Comment by katossky** [comment]
`height` issue : `geom_col` does work with numeric `x` and discrete `y` ; it should maybe accept `height` in that case ?

**Comment by katossky** [comment]
For the other issue, I did not say that you break anything ! Just that the result does not fit my expectations.

If :

```
ggplot2::diamonds |>
    dplyr::summarise(n=dplyr::n(), avgPrice=mean(price), .by=clarity) |>
    ggplot(aes(x=clarity, y=avgPrice)) +
    geom_col(fill=NA, color='black')
```

... produces :

image

I do not expect the columns to get crumble together when I add a `width` aesthetic.

**Comment by katossky** [comment]
So it was my understanding all along, sorry for that.

`width` indeed works with numeric `x` and discrete `y` (thank you) but I wrongly expected `height` there in alignment with `geom_tile`.

I was not expecting either `width` (_a priori_ something quantitative) to share the units with `x` (_a priori_ discrete) ! But I guess it may makes sense for consistency ?

```
ggplot2::diamonds |>
    dplyr::summarise(n=dplyr::n(), avgPrice=mean(price), .by=clarity) |>
    ggplot(aes(x=clarity, y=avgPrice, width = n / max(n))) +
    geom_col(fill=NA, color='black')
```

... indeed yields :

image

Last thing, in the preivous graph, I expected equal column spacing, irrespective of the width, as the only meaningful case I have in mind for variable-width column charts is this :

image

... but maybe I was wrong here again and that is not what you or anyone had in mind.

Thank you for your patience and clarification. Should I forward these comments somewhere where they are more useful ? Maybe am I not the only confused one ?

**Pull request merged**
