### PR TITLE
Restore names of guides after setup_panel_guides()

### LINKED ISSUE #5063: `Coord::train_panel_guides()` drops the names of guides
Guides are no longer named after `Coord::train_panel_guides()` is executed. This occurs in `Layout::setup_panel_guides()` which constructs the guides if they are missing and names them via `Coord::setup_panel_guides()`. 

The issue appears to be the addition of a line of code within `Coord::train_panel_guides()` with the `intersect()` function (copied here). `intersect` strips the names of the input character vector. 

The names of the guides help to link them with their associated scales, and the breaking of this link breaks code in an extension package. This change also undoes the preceding line, which sets the names. 

```r
    aesthetics <- c("x", "y", "x.sec", "y.sec")
    names(aesthetics) <- aesthetics

    # If the panel_params doesn't contain the scale, there's no guide for the aesthetic
    aesthetics <- intersect(aesthetics, names(panel_params$guides))
```

# Reprex
```r
library(ggplot2)
gg <- ggplot()
data <- ggplot_build(gg)

# Excerpt from ggplot_gtable.ggplot_built
plot <- data$plot
layout <- data$layout
data <- data$data

layout$setup_panel_guides(plot$guides, plot$layers, plot$mapping)

# Line showing change in outcome
names(layout$panel_params[[1]]$guides)
```

Expected output (and output prior to #3972 / commit 10eba36):
```r
[1] "x"     "y"     "x.sec" "y.sec"
```

Current output:
```r
NULL
```

### PR DESCRIPTION
**Pull request by maxsutton**
Fix #5063 

This fixes the names of aesthetics being dropped by `intersect()` by moving the assigning of names until after the `intersect()` call.

### CODE REVIEW

**Review by yutannihilation — APPROVED** [review]
Thanks! Sorry, this was my fault on implementing #3972.

This looks good to me. Do you think this is worth a NEWS item? If so, could you add one to `NEWS.md`?

**Comment by maxsutton** [comment]
All good! Added a line to `NEWS.md`.

**Review by yutannihilation — COMMENTED** [review]
Thanks! Sorry for nitpicking, but probably you meant `$` here?

**Comment by maxsutton** [comment]
> Thanks! Sorry for nitpicking, but probably you meant `$` here?

Thanks for picking that up!

**Pull request merged**
