### PR TITLE
Add arrow to line params

### PR DESCRIPTION
**Pull request by JakeRuss**
My vague recollection when I opened #4391, was I thought adding arrow was basically adding it to the list. As you can see from this commit it doesn't work. 

I expected the following to work, but no. 
````
library(sf)
library(ggplot2)

coords <- tibble::tibble(lat = c(26.562855, 28.538336), 
                         lon = c(-81.949532, -81.379234)) %>%
  st_as_sf(coords = c("lon", "lat"),  crs = 4326, remove = FALSE) %>%
  st_coordinates() %>%
  st_linestring()

ggplot() + 
  geom_sf(data = coords, size = 2, 
          arrow = arrow(angle = 45, ends = "last", type = "open", length = unit(0.5, "inches")))
````

I'm not sure I understand enough to complete this task

### CODE REVIEW

**Comment by clauswilke** [comment]
Arrows are not set in `gpar()`, they are set directly in the grob. See e.g. the documentation to `linesGrob()`. I suspect that if you add the arrow info here it will work:
https://github.com/tidyverse/ggplot2/blob/6d19950ec69e18dce119ae121059bae554ce421f/R/geom-sf.R#L216

**Comment by JakeRuss** [comment]
Thank you @clauswilke, that does seem to have done the trick. My example above now works

**Comment by clauswilke** [comment]
Maybe also add a visual test?

**Comment by JakeRuss** [comment]
My apologies, but I'm not sure what that means. If you could point me to an example I'd gladly add it.

**Comment by clauswilke** [comment]
See: https://vdiffr.r-lib.org/

Example:
https://github.com/tidyverse/ggplot2/blob/6e3ac8116195126d3cc843e50fca64bf6e4f43a4/tests/testthat/test-geom-sf.R#L177-L204

**Comment by JakeRuss** [comment]
Greatly appreciated, I will add

**Comment by JakeRuss** [comment]
@thomasp85 Ready to review at your schedule

**Comment by clauswilke** [comment]
@JakeRuss It looks like you didn't commit the new reference images for the two visual tests.

**Comment by JakeRuss** [comment]
@clauswilke Thank you for all of your pointers

**Comment by clauswilke** [comment]
The tests are failing. Please take a look. Looks like you need to write `sf::st_coordinates()` instead of just `st_coordinates()`. There may be other, similar issues once you fix this one.

**Comment by clauswilke** [comment]
`data_frame()` is a function defined by the ggplot2 codebase. It should not require a `tibble::` prefix. See also the other tests.

**Comment by clauswilke** [comment]
The reason why some of the tests still fail is because the reference images differ between the version you committed and the version generated in the github action. You may have outdated versions of some libraries. Not clear which ones, but if not vdiffr then possibly sf.

**Comment by JakeRuss** [comment]
Thanks, I will clean this up again today. I was running the testthat tests locally and it was complaining about data_frame, which I see now was because I didn't have it loaded.

**Review by clauswilke — APPROVED** [review]
Looks good to me.

@thomasp85 Any comments or concerns from your end?

**Review by thomasp85 — APPROVED** [review]

**Comment by thomasp85** [comment]
Thanks @JakeRuss !

**Pull request merged**
