### PR TITLE
Iron out binned limits and breaks

### LINKED ISSUE #5095: scale_binned() removes last bar when show.limits = TRUE
I am using geom_bar() and scale_x_binned() to make a histogram with the ticks between the bars.

R 3.6.2, ggplot2 3.3.5. Reproduced on R4.2.2 ggplot2 3.4.0 in this [SO case](https://stackoverflow.com/questions/74715943/r-histogram-scale-x-binned-gets-an-empty-last-bin-and-right-option-appears).

As documented in [this SO issue](https://stackoverflow.com/questions/74715943/r-histogram-scale-x-binned-gets-an-empty-last-bin-and-right-option-appears), the last bin is empty, and it appears to be related to the show.limits being true.

``` r
library(ggplot2)
library(Hmisc, warn.conflicts = FALSE)
#> Loading required package: lattice
#> Loading required package: survival
#> Loading required package: Formula

Time = c(17, 14, 21, 19, 18, 24, 25, 14, 17, 19, 20, 17, 21, 20, 23, 27, 25, 25, 27, 29, 24, 22, 26, 29)

# The last bin should be 28-30 and have a count of 2

data = data.frame(Time)

p <- ggplot(data, aes(x = Time)) +
  geom_bar()

p + scale_x_binned(right = FALSE, show.limits = TRUE)
#> Warning: Removed 1 rows containing missing values (`geom_bar()`).
```

``` r
p + scale_x_binned(right = FALSE, show.limits = FALSE)
```

<sup>Created on 2022-12-11 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

I tested with a function for the limits param, and could see that the passed original limits were set to c(14, 29).

### LINKED ISSUE #5100: position_dodge2(preserve="single") does not work on first bin with scale_x_binned()
I am using geom_bar() and scale_x_binned() to make a histogram with the ticks between the bars.

R 3.6.2, ggplot2 3.3.5. 

I am using preserve = "single" to make all bars equal width, as in the answer to[ this SO question](https://stackoverflow.com/questions/38101512/the-same-width-of-the-bars-in-geom-barposition-dodge).

It seems to work for most of the bins, but not the first bin. The actual dimensions of the first bin appear in fact to be all wrong:

image

Code to reproduce:

```r
rm(list=ls())
Program = c("LowCal", "LowCal", "LowCal", "LowCal", "LowFat", "LowFat", "LowFat", "LowFat", "LowFat", "LowFat", "LowCarb", "LowCarb", "LowCarb", "LowCarb", "LowCarb", "LowCarb", "LowCarb", "Control", "Control", "Control", "LowCal", "LowCal", "LowCal", "LowCal", "LowFat", "LowFat", "LowFat", "LowFat", "LowFat", "LowFat", "LowCarb", "LowCarb", "LowCarb", "LowCarb", "LowCarb", "LowCarb", "LowCarb", "Control", "Control", "Control")
Weight = c(8, 9, 6, 7, 4, 3, 6, 4, 7, 3, 4, 6, 5, 3, 4, 3, 3, 2, 2, 5, 8, 7, 6, 7, 3, 2, 4, 3, 5, 1, 3, 5, 4, 2, 3, 2, 2, 1, 1, 3)

data = data.frame(Program, Weight)

library(ggplot2)
library(Hmisc, warn.conflicts = FALSE)

xVar = data$Weight
zVar = data$Program

zVar = factor(zVar,
              levels = c("LowCal", "LowFat", "LowCarb", "Control"),
              labels = c("LowCal", "LowFat", "LowCarb", "Control")) 

ggplot(data,
   aes(x = xVar,
    fill = zVar))+

geom_bar(position = position_dodge2(preserve = "single"))+
scale_x_binned()+

scale_fill_manual(values = c("#5c368e", "#d54f53", "#92c94c", "#16a6a2"))+

scale_y_continuous(limits = NULL, expand = expansion(mult = c(0,0), add = c(0,0.05)))+

# Set the graph labels for both axes
xlab("Weight")+
ylab("Count")+

labs(fill = "Program")+

theme_bw()+
theme(
   legend.position = "right"
)
```

### PR DESCRIPTION
**Pull request by teunbrand**
This PR aims to fix #5095 and fix #5100.

A description of what probably went wrong is https://github.com/tidyverse/ggplot2/issues/5100#issuecomment-1345678426 and https://github.com/tidyverse/ggplot2/issues/5095#issuecomment-1345680678.

For your consideration, the reprexes of those two issues with this PR:

``` r
devtools::load_all("~/packages/ggplot2/")
#> ℹ Loading ggplot2

data <- data.frame(Time = c(17, 14, 21, 19, 18, 24, 25, 14, 17, 19, 20, 17, 21, 
                            20, 23, 27, 25, 25, 27, 29, 24, 22, 26, 29))

ggplot(data, aes(x = Time)) +
  geom_bar() +
  scale_x_binned(right = FALSE, show.limits = TRUE)
```

``` r
data <- data.frame(
  group = LETTERS[c(1L, 1L, 1L, 1L, 2L, 2L, 2L, 2L, 2L, 2L, 3L, 3L, 3L, 3L, 3L, 
                    3L, 3L, 4L, 4L, 4L, 1L, 1L, 1L, 1L, 2L, 2L, 2L, 2L, 2L, 2L, 
                    3L, 3L, 3L, 3L, 3L, 3L, 3L, 4L, 4L, 4L)],
  value = c(8, 9, 6, 7, 4, 3, 6, 4, 7, 3, 4, 6, 5, 3, 4, 3, 3, 2, 2, 5, 
            8, 7, 6, 7, 3, 2, 4, 3, 5, 1, 3, 5, 4, 2, 3, 2, 2, 1, 1, 3)
)

ggplot(data, aes(value, fill = group)) +
  geom_bar(position = position_dodge2(preserve = "single")) +
  scale_x_binned(show.limits = TRUE)
```

<sup>Created on 2022-12-12 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

### CODE REVIEW

**Comment by thomasp85** [comment]
The interplay between breaks and limits here is beginning to get quite convoluted. Can you add some unit tests to make sure we don't accidentally regress in the future?

**Comment by teunbrand** [comment]
Yeah agreed. I think this became more complicated because there is a sneaky state-modifying update to the limits in the `get_breaks()` method (though I understand why it might be there).

https://github.com/tidyverse/ggplot2/blob/853266c2bb240eeed35d5227115f33277ce76396/R/scale-.r#L1096

**Comment by thomasp85** [comment]
When `$map()` is called without the default `limit` argument will this still work? Can't remember when/if that occurs...

**Comment by teunbrand** [comment]
I think that happens all the time in guide training. I think it does the right thing by adapting to whatever limits you give it.

``` r
devtools::load_all("~/packages/ggplot2/")
#> ℹ Loading ggplot2

# Default limits
scale <- scale_x_binned(n.breaks = 20)
scale$train(c(1, 10))
scale$map(c(2, 8))
#> [1]  2 14
scale$get_breaks()
#>  [1] 1.5 2.0 2.5 3.0 3.5 4.0 4.5 5.0 5.5 6.0 6.5 7.0 7.5 8.0 8.5 9.0 9.5

# Custom smaller limits
scale <- scale_x_binned(n.breaks = 20)
scale$train(c(1, 10))
scale$map(c(2, 8), limits = c(4, 6))
#> [1]  1 20
scale$get_breaks()
#>  [1] 4.1 4.2 4.3 4.4 4.5 4.6 4.7 4.8 4.9 5.0 5.1 5.2 5.3 5.4 5.5 5.6 5.7 5.8 5.9

# Custom larger limits
scale <- scale_x_binned(n.breaks = 20)
scale$train(c(1, 10))
scale$map(c(2, 8), limits = c(-10, 20))
#> [1] 6 9
scale$get_breaks()
#>  [1] -8 -6 -4 -2  0  2  4  6  8 10 12 14 16 18
```

<sup>Created on 2023-01-09 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Review by thomasp85 — APPROVED** [review]
Got it - LGTM

**Pull request merged**
