### PR TITLE
Add documentation about `labs(tag = )`

### PR DESCRIPTION
**Pull request by yutannihilation**
`tag` argument seems not documented in `?labs` yet. Since `tag` is intended to be specified by `labs()`, I think this should be described here.

### CODE REVIEW

**Comment by yutannihilation** [comment]
Thanks! Of course the position is changeable, but "by default" is not added to other labels like `title`, whose positions are also changeable. Does adding "by default" only to `tag` make sense?

**Comment by clauswilke** [comment]
Rereading it all in context, I'm fine with it as is.

One other small issue I noticed, however: In the "Details" section, there's a parenthesis that isn't closed: "You can also set axis and legend labels in the individual scales (using the first argument, the `name`." Would you mind closing it?

**Comment by yutannihilation** [comment]
Sure, will do later.

**Comment by yutannihilation** [comment]
Done!

**Comment by hadley** [comment]
@yutannihilation if you wanted to make it even better, I think `labs()` could use named arguments for `title`, `caption` etc. That'll make the function easier to use, and the documentation more clear.

**Comment by yutannihilation** [comment]
@hadley Thanks, agreed. I've wondered why they are not named args...🙄 Do you mean I should create another PR for this? If so, I'll try tomorrow. But, if you will do, I'm ok.

**Comment by hadley** [comment]
A PR would be awesome 😄 (and no rush, since this shouldn't affect any code; although it might be useful to have some tests to verify that)

**Comment by yutannihilation** [comment]
Sure!

**Pull request merged**
