### PR TITLE
feat: add DocSearch as recommended by pkgdown

### PR DESCRIPTION
**Pull request by s-pace**
👋 team,

I am working on DocSearch. [We have an integration for pkgdown](https://pkgdown.r-lib.org/). We thought it is a shame you can not also used this search.

This PR will add DocSearch to the documentation website. It will allow a user to have a learn-as-you-type experience by displaying results thanks to a dropdown in a live way.

Let me know if you need anything.

### CODE REVIEW

**Comment by yutannihilation** [comment]
DocSearch was added by #3370 and then removed by #3374. I don't know about the detail, but it seems DocSearch didn't work at that time.

@batpigandme 
Do you think this is worth trying again?

**Comment by s-pace** [comment]
It is now working yes

**Comment by batpigandme** [comment]
Yeah, if it's working, then, sure thing.

**Comment by s-pace** [comment]
It is https://docsearch.algolia.com/playground/?indexName=tidyverse_ggplot2&apiKey=e1261f3df95d2d4704c626ff11a4b536

**Comment by yutannihilation** [comment]
Thanks, so the previous mistake was that we used the same key (`tidyverse`) over multiple repositories, right? Then, I have no concern.

One more question. Can we use this API key? It seems there are already several API keys used among tidyverse and r-lib repositories, but I don't know how they are managed...

* https://github.com/search?q=docsearch+org%3Atidyverse+filename%3Apkgdown.yml
* https://github.com/search?q=docsearch+org%3Ar-lib+filename%3Apkgdown.yml

**Comment by s-pace** [comment]
Yes it is one key for a website

**Comment by yutannihilation** [comment]
Thanks.

**Comment by yutannihilation** [comment]
What I'm still not sure is that which is better to use the API key here or the new one someone in the tidyverse team issues, but I think it's fine to merge this PR anyway as we can replace the key anytime.

I'll wait for some days before merging this. If you have any other concern, please comment.

**Comment by yutannihilation** [comment]
Merged. Thanks @s-pace for catching this :)

**Pull request merged**
