### PR TITLE
Fix warning when using weight with stat_bin

### PR DESCRIPTION
**Pull request by jiho**

### CODE REVIEW

**Comment by jiho** [comment]
A warning is emitted although it seems to be doing the right thing.

```r
library("ggplot2")
d <- data.frame(x=c(1,1,2), y=c(1,1,10))
ggplot(d) + geom_histogram(aes(x=x), binwidth=1)
ggplot(d) + geom_histogram(aes(x=x, weight=y), binwidth=1)
```
```
Warning: Ignoring unknown aesthetics: weight
```

`geom_bar` does not display the problem. This simple commit fixes the warning and seems appropriate.

**Comment by hadley** [comment]
Could you please add a bullet to NEWS?

**Comment by jiho** [comment]
Not sure where. Above `# ggplot2 2.2.0`

**Comment by hadley** [comment]
Ooops, forgot to push. Try now

**Comment by jiho** [comment]
Done. I squashed everything.

**Comment by hadley** [comment]
Thanks!

**Pull request merged**
