### PR TITLE
Add link to authors in pkgdown

### LINKED ISSUE #3852: Setup _pkgdown.yml authors metadata
So all authors (not just me) get a link to their website

### PR DESCRIPTION
**Pull request by thomasp85**
Fixes #3852 

@clauswilke, @kohske, @yutannihilation, @wch, @lionel-, @karawoo, @paleolimbot can you all please reply with your preferred link, or whether you'd rather not want to link to anything

### CODE REVIEW

**Comment by yutannihilation** [comment]
Thanks. My link is https://yutani.rbind.io/

**Comment by clauswilke** [comment]
For me, please use: https://clauswilke.com/

**Comment by karawoo** [comment]
https://karawoo.com/ please!

**Comment by wch** [comment]
https://github.com/wch for me. Thanks!

**Comment by lionel-** [comment]
https://github.com/lionel- thanks!

**Comment by thomasp85** [comment]
While we are at it. Is anyone interested in having their orchid ID in the description? You'll get a nice little icon link on the pkgdown site as well... @Hadley this goes for you as well

**Comment by hadley** [comment]
My ORCID is 0000-0003-4757-117X

**Comment by clauswilke** [comment]
ORCID: 0000-0002-7470-9261

**Comment by yutannihilation** [comment]
My ORCID is 0000-0002-3385-7233.

**Comment by wch** [comment]
My ORCID is 0000-0002-1576-2126.

**Comment by karawoo** [comment]
0000-0002-5125-4188

**Pull request merged**
