### PR TITLE
Don't export LayerSf

### LINKED ISSUE #3158: Don't export LayerSf
When I implemented custom layers for sf objects, I exported the relevant layer object, `LayerSf()`:
https://github.com/tidyverse/ggplot2/blob/033fb521a084447c15178c591ab96a158f3b1e1e/R/layer-sf.R#L3-L8

This is bad, because we currently don't export its parent, `Layer()`, and we don't want to export it at this time.

The correct way to make the sf-specific layer available is to add a constructor function, `layer_sf()`, which replaces the `layer()` function for sf layers.

### PR DESCRIPTION
**Pull request by thomasp85**
Fix #3158 This will undo the export of `LayerSf`

### CODE REVIEW

**Comment by thomasp85** [comment]
I'll merge it now as it may otherwise be lost in the process... the `layer_type` argument is something we can have another time I think...

**Comment by clauswilke** [comment]
I’m more concerned that we have unexported `LayerSf` but haven’t added `layer_sf()` yet. This may have downstream implications for packages under development, e.g. ggrepel. @yutannihilation is the person most likely to have such code floating around somewhere.

**Comment by yutannihilation** [comment]
Thanks for mentioning me! I think it's fine not to add `layer_sf()`. We can add it when we get sure it's needed.

One thing, do you think we can remove `layer_class` argument of `layer()`? Though this argument is visible to users, this is not usable because no `Layer` class is exported.

https://github.com/tidyverse/ggplot2/blob/033fb521a084447c15178c591ab96a158f3b1e1e/R/layer.r#L66

It's not necessary but nice if we can remove this to avoid confusion.

**Comment by yutannihilation** [comment]
Ah, sorry I missed this comment: https://github.com/tidyverse/ggplot2/issues/3207#issuecomment-477293511

OK, let's leave `layer_class` and do this:

> We could add "for ggplot2 internal use only" to the documentation to make this clear.

**Pull request merged**
