### PR TITLE
Move the check on misuse of data.frame() to tests

### PR DESCRIPTION
**Pull request by yutannihilation**
#3526 introduced the static analysis of codes here.

https://github.com/tidyverse/ggplot2/blob/214f3148d8a9a25ce80859645dbef38f9632b4fa/tests/testthat/test-conditions.R#L3-L21

This approach seems very clean and extensive because this catches the misuse of the prohibited function even if it's on the rare code path. I think the check on `data.frame()` should be done in the same way instead of overwriting the function. One bonus of this is that we'll be less likely to face such mysterious issues as #3745.

### CODE REVIEW

**Comment by clauswilke** [comment]
I like this approach, but I'd like to suggest that we should also test the test (i.e., include a true positive). Add a file to the testthat directory that contains the prohibited functions and check that the counts of prohibited functions for that file are correct.

**Comment by yutannihilation** [comment]
Thanks, I added some simple tests.

**Comment by thomasp85** [comment]
@yutannihilation can we merge this in in its current form?

**Comment by yutannihilation** [comment]
Yes, since this is just about testing, I think it's safe to merge this.

**Review by thomasp85 — APPROVED** [review]
LGTM

**Comment by yutannihilation** [comment]
Thanks

**Pull request merged**
