### PR TITLE
Don't let codecov fail build with "No report found to compare against"

### PR DESCRIPTION
**Pull request by jennybc**
From here: https://github.com/codecov/support/issues/173#issuecomment-216067683

This might help with codecov failing to find a report for the base commit. Let's find out ...

### CODE REVIEW

**Comment by jennybc** [comment]
It looks like this has been an ongoing problem that is, in theory, fixed, but in reality maybe not, based on all the +1's here: https://github.com/codecov/support/issues/363

So it might be reasonable to simply not allow codecov to fail a build for this reason. Which is the intent of this PR.

**Comment by karawoo** [comment]
@hadley shall we give this a try? It seems to have (retroactively??) fixed the codecov issue in #2179. I guess the other option is "just pray codecov sorts itself out" -- my last PR (#2190) didn't have any problems.

**Comment by jennybc** [comment]
It seems like you got your codecov failures for inexplicable and self-resolving reasons. Which I have also experienced. I'd err on the side of not doing anything rash unless the problem persists.

It would be different if codecov was failing builds due to picky reasons about coverage percentage. I would take control of that in the yaml. But this "no report" error is a different problem.

**Comment by hadley** [comment]
Ok, let's leave for now, and if we don't see any more problems we can close this PR.

**Pull request closed without merging**
