### PR TITLE
Update limits.r

### PR DESCRIPTION
**Pull request by ismayc**
Fix typo in documentation for specification of Arguments of `limits()` function

### CODE REVIEW

**Comment by yutannihilation** [comment]
Thanks!

**Comment by ismayc** [comment]
You're welcome! Sorry for not following instructions on building documentation too, but you did teach me about how to get that to work with GitHub Actions, so a bigger thanks to you 😄

**Comment by yutannihilation** [comment]
Yeah, GitHub Actions is a thing. You can find the details and other useful actions at https://github.com/r-lib/actions/tree/master/examples#commands-workflow

**Comment by ismayc** [comment]
Thanks. I knew about those GitHub Actions examples, but apparently didn't read over them close enough on first glance. Great stuff!

**Pull request merged**
