### PR TITLE
Squish infinite values in coord_sf(), coord_map(), and coord_polar()

### LINKED ISSUE #2971: Unable to add text annotation to geom_sf plot
I would like to use relative positioning (0-1 scale) to add a text annotation to a ggplot object that uses geom_sf.  I've tried two different methods that were mentioned [here](https://github.com/tidyverse/ggplot2/issues/1244), but both seem to fail with different results. 

First attempt, using Hadley's [suggestion](https://github.com/tidyverse/ggplot2/issues/1244#issuecomment-128021830) does produce any annotation:
```
library(ggplot2)
ggplot(nc, aes(fill=AREA)) + 
  geom_sf() + 
  annotate("text", -Inf, Inf, label = "Top-left", hjust = 0, vjust = 1)
```
I never see "Top-left" on the plot no matter what values I've tried for hjust or vjust.

Second attempt, using textGrob (via [this comment](https://github.com/tidyverse/ggplot2/issues/1244#issuecomment-263666211)):
```
library(sf)
library(ggplot2)
library(grid)
nc = st_read(system.file("shape/nc.shp", package="sf"))
ggplot(nc) +geom_sf(aes(fill = AREA))+
	annotation_custom(textGrob(label="xx"))
```
This results in `"Error in grid.Call.graphics(C_setviewport, vp, TRUE): non-finite location and/or size for viewport"`.  I get the same results if I specify x and y locations in textGrob with different units (npc, cm, lines). 

Any help would be most welcome.  Thanks.

(This was originally posted to the sf repo but was posted here at the suggestion of [yutannihilation](https://github.com/r-spatial/sf/issues/879#issuecomment-434853524) who said "I guess coord_sf() forgets to squash Inf within the range, which coord_cartesian() does.")

### PR DESCRIPTION
**Pull request by yutannihilation**
Fixes #2971 (and r-spatial/sf#879)

It seems `CoordSf`, `CoordMap`, and `CoordPolar` don't follow the convention of treating `Inf` as the edge of the range. This PR fixes it.

### `CoordSf`

It seems `CoordSf$transform()` just forget to squish infinite values to range as `coord_cartesian()` does. 

### `CoordMap`

In `CoordMap`, `Inf` can be converted to `NA` by `mapproj:: mapproject()`. So, just applying `squish_infinite()` is not enough; we need to restore the `Inf` from the original data.

### `CoordPolar`

For angle (`theta`), `Inf` and `-Inf` are squashed into `0`, which is both the start and the end of the circle. For radius (`r`), `Inf` is squashed to `0.4`, the hardcoded value in `r_rescale()`, and `-Inf` is squashed to `0`.

## Results

``` r
library(ggplot2)

ggplot(sf::st_point(c(0, 0))) +
  geom_sf() +
  annotate("text", -Inf, Inf, label = "Top-left", hjust = 0, vjust = 1)
```

``` r

ggplot(data.frame(x = 0, y = 0)) +
  geom_point(aes(x,y)) +
  annotate("text", -Inf, Inf, label = "Top-left", hjust = 0, vjust = 1) +
  coord_map()
```

``` r

ggplot(data.frame(x = "a", y = 1), aes(x, y)) +
  geom_col(fill = "white") +
  coord_polar() +
  annotate("text", Inf, Inf, label = "Top-Center") +
  annotate("text", -Inf, -Inf, label = "Center-Center")
```

<sup>Created on 2018-11-26 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

### CODE REVIEW

**Comment by clauswilke** [comment]
This seems reasonable to me. Are there other coords that have the same issue?

**Comment by yutannihilation** [comment]
Thanks, here's a table of `transform()`s. To me,

* `CoordCartesian` and `CoordTrans` are fine.
* `CoordFlip` is fine since it uses `CoordCartesian$transform()` inside.
* `CoordFixed` and `CoordQuickmap` are fine since they inherit from `CoordCartesian`.
* `CoordSf` needs to be fixed.
* `CoordMap` seems to have the same issue, so I'll fix this as well.
* `CoordPolar` seems to have the same issue, but I'm yet to find what it means to "squash infinite values to range" in this coordination system...

``` r
library(ggplot2)
library(purrr)

e <- as.environment("package:ggplot2")
coords_names <- ls(e, pattern = "^Coord")
coords <- map(set_names(coords_names), get, envir = e)

transforms <- coords %>%
  map("transform") %>%
  map(rlang::expr_text) %>%
  map(sprintf, fmt = '<div class="highlight highlight-source-r"><pre>%s</pre></div>')

knitr::kable(
  tibble::enframe(transforms),
  format = "html",
  escape = FALSE
)
```

<table>

<thead>

<tr>

<th style="text-align:left;">

name

</th>

<th style="text-align:left;">

value

</th>

</tr>

</thead>

<tbody>

<tr>

<td style="text-align:left;">

Coord

</td>

<td style="text-align:left;">

<div class="highlight highlight-source-r">

<pre>function (data, range) 
NULL</pre>

</div>

</td>

</tr>

<tr>

<td style="text-align:left;">

CoordCartesian

</td>

<td style="text-align:left;">

<div class="highlight highlight-source-r">

<pre>function (data, panel_params) 
{
    rescale_x <- function(data) rescale(data, from = panel_params$x.range)
    rescale_y <- function(data) rescale(data, from = panel_params$y.range)
    data <- transform_position(data, rescale_x, rescale_y)
    transform_position(data, squish_infinite, squish_infinite)
}</pre>

</div>

</td>

</tr>

<tr>

<td style="text-align:left;">

CoordFixed

</td>

<td style="text-align:left;">

<div class="highlight highlight-source-r">

<pre>NULL</pre>

</div>

</td>

</tr>

<tr>

<td style="text-align:left;">

CoordFlip

</td>

<td style="text-align:left;">

<div class="highlight highlight-source-r">

<pre>function (data, panel_params) 
{
    data <- flip_labels(data)
    CoordCartesian$transform(data, panel_params)
}</pre>

</div>

</td>

</tr>

<tr>

<td style="text-align:left;">

CoordMap

</td>

<td style="text-align:left;">

<div class="highlight highlight-source-r">

<pre>function (self, data, panel_params) 
{
    trans <- mproject(self, data$x, data$y, panel_params$orientation)
    out <- cunion(trans[c("x", "y")], data)
    out$x <- rescale(out$x, 0:1, panel_params$x.proj)
    out$y <- rescale(out$y, 0:1, panel_params$y.proj)
    out
}</pre>

</div>

</td>

</tr>

<tr>

<td style="text-align:left;">

CoordPolar

</td>

<td style="text-align:left;">

<div class="highlight highlight-source-r">

<pre>function (self, data, panel_params) 
{
    data <- rename_data(self, data)
    data$r <- r_rescale(self, data$r, panel_params)
    data$theta <- theta_rescale(self, data$theta, panel_params)
    data$x <- data$r * sin(data$theta) + 0.5
    data$y <- data$r * cos(data$theta) + 0.5
    data
}</pre>

</div>

</td>

</tr>

<tr>

<td style="text-align:left;">

CoordQuickmap

</td>

<td style="text-align:left;">

<div class="highlight highlight-source-r">

<pre>NULL</pre>

</div>

</td>

</tr>

<tr>

<td style="text-align:left;">

CoordSf

</td>

<td style="text-align:left;">

<div class="highlight highlight-source-r">

<pre>function (self, data, panel_params) 
{
    data[[geom_column(data)]] <- sf_rescale01(data[[geom_column(data)]], 
        panel_params$x_range, panel_params$y_range)
    data <- transform_position(data, function(x) sf_rescale01_x(x, 
        panel_params$x_range), function(x) sf_rescale01_x(x, 
        panel_params$y_range))
    data
}</pre>

</div>

</td>

</tr>

<tr>

<td style="text-align:left;">

CoordTrans

</td>

<td style="text-align:left;">

<div class="highlight highlight-source-r">

<pre>function (self, data, panel_params) 
{
    trans_x <- function(data) transform_value(self$trans$x, data, 
        panel_params$x.range)
    trans_y <- function(data) transform_value(self$trans$y, data, 
        panel_params$y.range)
    new_data <- transform_position(data, trans_x, trans_y)
    warn_new_infinites(data$x, new_data$x, "x")
    warn_new_infinites(data$y, new_data$y, "y")
    transform_position(new_data, squish_infinite, squish_infinite)
}</pre>

</div>

</td>

</tr>

</tbody>

</table>

<sup>Created on 2018-11-01 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by yutannihilation** [comment]
Hmm, `coord_map()` does have the same problem, but it seems the same fix is not enough...

``` r
library(ggplot2)

p <- ggplot(data.frame(x = 0, y = 0)) +
  geom_point(aes(x,y)) +
  annotate("text", -Inf, Inf, label = "Top-left", hjust = 0, vjust = 1)

patchwork::wrap_plots(
  p + coord_map(),
  p + coord_quickmap()
)
```



<sup>Created on 2018-11-01 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

The problem is that `CoordMap$transform()` converts `Inf` to `NA` because underlying `mapproj::mapproject()` does so. But, `mapproj::mapproject()` originally perservers `Inf`. After building a plot, the same function returns different result. What happened...?

``` r
library(ggplot2)

mapproj::mapproject(data.frame(x = c(-Inf, 0, 1), y = c(0, 1, Inf)))
#> $x
#> [1] -Inf    0    1
#> 
#> $y
#> [1]   0   1 Inf

p <- ggplot(data.frame(x = 0, y = 0)) +
  geom_point(aes(x,y)) +
  annotate("text", -Inf, Inf, label = "Top-left", hjust = 0, vjust = 1) +
  coord_map()

b <- ggplot_build(p)

mapproj::mapproject(data.frame(x = c(-Inf, 0, 1), y = c(0, 1, Inf)))
#> $x
#> [1] NA  0 NA
#> 
#> $y
#> [1]         NA 0.01745418         NA
#> 
#> $range
#> [1] 0.00000000 0.00000000 0.01745418 0.01745418
#> 
#> $error
#> [1] 1
```

<sup>Created on 2018-11-01 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by yutannihilation** [comment]
This also needs to wait for #3003.

**Comment by yutannihilation** [comment]
Ah, sorry, I forgot to add a NEWS bullete... Will add one and merge.

**Pull request merged**
