### PR TITLE
Makes ggsave return invisibly plot filename.

### PR DESCRIPTION
**Pull request by eliocamp**
I realised that implementing #3379 needed only the slightest change, so I could do it :).

### CODE REVIEW

**Comment by clauswilke** [comment]
@thomasp85 Should we merge this? Looks reasonable to me.

**Comment by thomasp85** [comment]
@eliocamp can you merge in master and add a news bullet - then we can merge this in for the next release

**Comment by eliocamp** [comment]
I rebased and added the news bullet (I never know if I need to add it at the beginning or at the end).

**Comment by clauswilke** [comment]
@eliocamp For future reference, it's much better if you merge in master rather than rebase. Rebasing creates this long list of commits and files changed that is extremely difficult to review. In the end, we squash-merge anyways, so the final commit to the ggplot code base will look the same regardless of whether you rebase or merge.

**Comment by clauswilke** [comment]
Yes, just start over.

**Pull request closed without merging**
