### PR TITLE
follow tidyverse recycling rules for aesthetics

### LINKED ISSUE #4588: Misleading error message when plotting with empty data.frame
When plotting with an empty data (which may happen when filtering goes wrong), there is an error if constant aesthetics are mixed with column names, and the error message is a little confusing.

Example:
```r
> ggplot(head(mtcars, 0)) + geom_point(aes(x = hp, y = mpg)) # no error here, plot is empty
> ggplot(head(mtcars, 0)) + geom_point(aes(x = 3, y = 4))        # no error here, plot contains one point
> ggplot(head(mtcars, 0)) + geom_point(aes(x = 3, y = mpg))   # error!
 Fehler: Aesthetics must be either length 1 or the same as the data (1): y
Run `rlang::last_error()` to see where the error occurred. 
```

Taken literally, the error message is wrong: Aesthetics `y` does have the same length as the data (0).

Expected behaviour: No error message, return an empty plot.

### PR DESCRIPTION
**Pull request by thomasp85**
Fix #4588 

This PR allows mix of 0-length and 1-length vectors (recycled to 0) in aesthetics... It both puts ggplot2 in line with our decided recycling rules and makes it less error-prone to set aesthetics to scalars as these values can now be mixed with all sizes of data (even 0)

### CODE REVIEW

**Comment by hadley** [comment]
Add a small test?

**Comment by jubilatious1** [comment]
I'm not sure I understand. A variable of length-zero assigned an aesthetic is effectively an "option" in R, is it not? 

`Aesthetics of length 1 are now recycled to 0 if the length of the data is 0 `

So zero-length data (effectively NAs) cause their calling Aesthetics to assume NA values as well?

**Comment by hadley** [comment]
@jubilatious1 NA has length 1, not length 0. You can read about the tidyverse recycling rules at https://vctrs.r-lib.org/articles/type-size.html#size-1, but this PR is not the right place for discussion of them.

**Comment by jubilatious1** [comment]
Thank you.

**Review by hadley — APPROVED** [review]

**Pull request merged**
