### PR TITLE
Fix a bug about strip.placement in facet_wrap()

### LINKED ISSUE #3045: Error from facet_wrap(strip.position = "bottom") + theme_void()
- OK: `facet_wrap(~cyl, ncol = 2L, strip.position = "bottom") + theme_grey()`
- NG: `facet_wrap(~cyl, ncol = 2L, strip.position = "bottom") + theme_void()`
- OK: `facet_wrap(~cyl, ncol = 2L, strip.position = "left") + theme_void()`
- OK: `facet_wrap(~cyl, ncol = NULL, strip.position = "bottom") + theme_void()`

It is observed with both release 3.1.0 and `master`

```r
ggplot(mtcars, aes(disp, mpg)) +
  geom_point() +
  facet_wrap(~cyl, ncol = 2L, strip.position = "bottom") +
  theme_void()
# Error in if (params$strip.position == "bottom" && theme$strip.placement !=  :
#   missing value where TRUE/FALSE needed
# Calls: <Anonymous> ... ggplot_gtable.ggplot_built -> <Anonymous> -> f -> <Anonymous> -> f
```

### PR DESCRIPTION
**Pull request by yutannihilation**
Fix #3045 

When `theme$strip.placement` is `NULL`, it should be treated as `"inside"`. It might be better if that default value is set when theme is created, but I just want to fix the apparent inconsistency for now.

``` r
library(ggplot2)

ggplot(mtcars, aes(disp, mpg)) +
  geom_point() +
  facet_wrap(~cyl, ncol = 2L, strip.position = "bottom") +
  theme_void()
```

<sup>Created on 2018-12-27 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

### CODE REVIEW

**Comment by yutannihilation** [comment]
@clauswilke Could you review this when you have a chance? I expect #2784 will fix this kind of problems fundamentally, so I'm not fully sure we need this particular fix or not. If you think this is not necessary, I'll close this.

**Comment by clauswilke** [comment]
Could you ask @thomasp85 for a review? I am currently traveling, and I don't know this code very well.

**Comment by yutannihilation** [comment]
@clauswilke Oh, sorry. Sure. Have a nice trip.

**Comment by yutannihilation** [comment]
Thanks!

**Pull request merged**
