### PR TITLE
Fix issue 4527

### PR DESCRIPTION
**Pull request by clauswilke**
Creating PR against master for now so the automated tests are run.

### CODE REVIEW

**Comment by clauswilke** [comment]
@thomasp85 Sorry, I don't quite know the right flow when working with a branch. I checked out v3.3.5-rc. Should I set up the PR against that branch also? Will CI run then?

**Comment by thomasp85** [comment]
Test should run no matter what branch you want to merge into - the only difference I've noticed is that issues are not automatically closed if a PR is merged into something other than master

Are you confident that this change doesn't have any negative impact? Or should I run a revue-check?

**Comment by clauswilke** [comment]
> Are you confident that this change doesn't have any negative impact?

I'm never confident about that. :-) A revdep-check wouldn't hurt.

The transformation function aborts if either the two crs's are the same or if one is `NULL`. So whether we explicitly set the default crs equal to the layer crs or set it to `NULL` shouldn't make any difference. I think early in writing this code I was thinking that `default_crs` would have to actually take on a value at some point during rendering, but that's actually more difficult to reason about than just keeping it `NULL` throughout.

https://github.com/tidyverse/ggplot2/blob/389b864657821e967ba50fbf5097b135c22ec0a4/R/coord-sf.R#L504-L510

Obviously if the `default_crs` parameter is set to some value none of this matters. Maybe I should catch that possibility in the `is_linear()` function also. Let me try this out and possibly make another commit.

**Comment by thomasp85** [comment]
👍 I'll run a revdepcheck when you ping me

**Comment by clauswilke** [comment]
Sorry, never mind, that requires a bunch of other changes that I don't want to make now. I think this PR is our best bet. If you have a bunch of sf plotting code that you could run manually to test that would be great. I have done so and haven't seen any issues, and the tests pass, but we know about these pesky corner cases. :-)

**Comment by clauswilke** [comment]
Closing this PR so I can open one for the release branch.

**Pull request closed without merging**
