### PR TITLE
Typo in geom-map.R

### PR DESCRIPTION
**Pull request by jonocarroll**
Minor typo in documentation.

### CODE REVIEW

**Comment by teunbrand** [comment]
\document

**Comment by jonocarroll** [comment]
Interesting; shouldn't the .Rd files be generated artefacts and thus whatever is committed is redundant? In any case, I've re-generated and committed the relevant file.

**Comment by teunbrand** [comment]
Thanks for the update!
AFAIK we have no mechanism in place to automate regenerating the docs.
I think {gtable} has had a recent update that borks some tests that fail.
These are unrelated to your PR, so I'll approve this and merge when we've updated the tests.

**Review by teunbrand — APPROVED** [review]

**Comment by teunbrand** [comment]
Thank you for the contribution!

**Pull request merged**
