### PR TITLE
Update link in docu

### PR DESCRIPTION
**Pull request by katrinleinweber**
Hello :-) Is it intended that this link directs to the package-level docu, instead of the relevant function?

### CODE REVIEW

**Comment by yutannihilation** [comment]
Thanks! Could you regenerate the documents by `devtools::document()`? If you don't know how to do, don't worry, we'll take care of it.

**Comment by katrinleinweber** [comment]
Will do in the next few days. Thanks for the hint!

**Comment by katrinleinweber** [comment]
Sure :-) Like this?

**Comment by katrinleinweber** [comment]
You're welcome & thanks for merging :-)

**Pull request merged**
