### PR TITLE
Enable 2D structures as aesthetics

### LINKED ISSUE #4189: Feature request: support for tibble aesthetics
I'm developing a ggplot2 extension where it would be helpful to pass a tibble column as an aesthetic.

As a simple motivating example, you could imagine a `geom_box()` layer with a `bounds` aesthetic that expects a tibble with columns xmin, ymin, xmax and ymax. Then I could simply do `geom_box(bounds = bbox)` and the layer will use the nested columns to draw the box.

To do this, we need to make use of nested tibbles (i.e. a tibble column within a tibble).

``` r
library(tidyverse)

dat <- tibble(a = tibble(x = 1:5, y = 6:10))

# works fine
ggplot(dat) +
  geom_point(aes(x = a$x, y = a$y))
```

So far, so good. But these aesthetics are still just vectors. Let's try using the tibble column `a`.

(Obviously, `geom_point()` doesn't expect a tibble column for its `x` aesthetic, but it _does_ generate the relevant error.)

``` r
ggplot(dat) +
  geom_point(aes(x = a, y = a$y))
#> Don't know how to automatically pick scale for object of type tbl_df/tbl/data.frame. Defaulting to continuous.
#> Error: Aesthetics must be either length 1 or the same as the data (5): x
```

The warning can be removed with a new `scale_type`. But the error is generated by this line: https://github.com/tidyverse/ggplot2/blob/813d0bd8c7d4df3b3cba170de54233076b346c1c/R/geom-.r#L211

The length of a data frame is the number of columns (2) instead of the number of rows (5), so we get this error. This is the same problem that `vctrs::vec_size()` addresses.

Would it be possible to simply avoid this error by replacing `length()` with `nrow()`, `NROW()` or `vec_size()`? Or would there be other repercussions?

### LINKED ISSUE #6090: Feature request: accept data.frame as scale `labels`
This is a very niche and selfish problem as I'm trying some stuff out in {gguidance}.
It somewhat relates to #6076 a bit, but I'd like the following code:

``` r
library(ggplot2)

p <- ggplot(mpg, aes(displ, hwy)) +
  geom_point() +
  scale_x_continuous(
    breaks = 2:7,
    labels = data.frame(foo = LETTERS[1:6], bar = 1:6)
  )

get_guide_data(p, aesthetic = "x")
#> Error in `scale_x_continuous()`:
#> ! `breaks` and `labels` have different lengths.
```

<sup>Created on 2024-09-07 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

To return the following data.frame (note that the `.label` column is a nested data.frame rather than two separate `.label.foo` and `.label.bar` columns):

```r
#>           x .value .label.foo .label.bar y
#> 1 0.1127946      2          A          1 0
#> 2 0.2811448      3          B          2 0
#> 3 0.4494949      4          C          3 0
#> 4 0.6178451      5          D          4 0
#> 5 0.7861953      6          E          5 0
#> 6 0.9545455      7          F          6 0
```

The justification I have for this is that {vctrs} treats data.frames as vectors where rows are treated as elements. We don't really have a good reason to deviate from this behaviour.

### PR DESCRIPTION
**Pull request by teunbrand**
This PR aims to fix #4189 and fix #6090.

Briefly, this PR would allow people to use 2D structures like matrices, data.frames and tibbles as aesthetics.
We just had to adopt the {vctrs} way of measure sizes and setting names at select places for this to.
Importantly, this does *not* implement appropriate scales for such aesthetics, but it removes a barrier for extension developers to implement them.

``` r
devtools::load_all("~/packages/ggplot2/")
#> ℹ Loading ggplot2

df <- mtcars
df$tib <- tibble::tibble(mpg = df$mpg, disp = df$disp)
df$mtx <- cbind(mpg = df$mpg, disp = df$disp)

p <- ggplot(df, aes(cyl, disp, dummy = tib)) +
  geom_point()

layer_data(p)$dummy |> head()
#> Don't know how to automatically pick scale for object of type
#> <tbl_df/tbl/data.frame>. Defaulting to continuous.
#> # A tibble: 6 × 2
#>     mpg  disp
#>   <dbl> <dbl>
#> 1  21     160
#> 2  21     160
#> 3  22.8   108
#> 4  21.4   258
#> 5  18.7   360
#> 6  18.1   225

layer_data(p + aes(dummy = mtx))$dummy |> head()
#>       mpg disp
#> [1,] 21.0  160
#> [2,] 21.0  160
#> [3,] 22.8  108
#> [4,] 21.4  258
#> [5,] 18.7  360
#> [6,] 18.1  225
```

<sup>Created on 2024-09-04 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

### CODE REVIEW

**Comment by teunbrand** [comment]
I'm unsure why the coverage CI is failing

**Comment by teunbrand** [comment]
TODO: check errors in scales

**Comment by teunbrand** [comment]
Also incorporated #6090 as it is thematically related in the sense of "ggplot2 should give vctrs treatment to input".

**Review by thomasp85 — APPROVED** [review]
LGTM

**Pull request merged**
