### PR TITLE
Remove maptools and deprecate fortify() for sp objects

### PR DESCRIPTION
**Pull request by yutannihilation**
A part of #5244

While we lean to agree on dropping these `fortify()` for sp objects altogether, there might be several options. At the safest, we should remove maptools, because otherwise ggplot2 might be kicked out from CRAN in the worst-case scenario. So, this pull request does

1. remove maptools
2. deprecate `fortify()` for sp objects in general

### CODE REVIEW

**Review by teunbrand — APPROVED** [review]
LGTM, but would it make sense to be a little bit more explicit why people need to migrate to {sf}?
For example: "The maptools package {is/will be} retired: please migrate to sf."

**Comment by teunbrand** [comment]
Right, I might've skimmed over the nuance here. In any case it was merely a suggestion, I think this PR is fine as-is.

**Comment by teunbrand** [comment]
@yutannihilation There were no reverse dependency issues with retiring maptools and it would be nice to include this PR in the hotfix for v3.4.4, as maptools retires in October. If you'd like, I'm happy to merge this in to the v3.4.4-rc and tweak the version number. If you prefer changing the target branch and changing the version number in deprecation messages yourself, that is great too.

**Comment by yutannihilation** [comment]
> If you prefer changing the target branch and changing the version number in deprecation messages yourself, that is great too.

I'm fine with either, but, in my understanding, this needs to be merged into the main branch anyway, no matter whether this is merged into the RC branch or not, right?

**Comment by thomasp85** [comment]
The RC branch will be merged into main after release

**Comment by thomasp85** [comment]
Ah, you already merged in main. Yeah, then merging this PR and cherry picking the commit is probably the right way

**Comment by thomasp85** [comment]
hmm - can you try to change the target of the PR and see what it will change... I don't think it will bring in all the prior changes, but maybe I'm wrong

**Comment by teunbrand** [comment]
I'm not very wise in the ways of git-fu but isn't there a way to rebase a branch to 'play out' the commits over a different branch?

**Comment by yutannihilation** [comment]
Oops, I'm sorry. I actually tried to do this

> I'm not very wise in the ways of git-fu but isn't there a way to rebase a branch to 'play out' the commits over a different branch?

but accidentally pushed into `v3.4.4-rc` directly...

https://github.com/tidyverse/ggplot2/commits/v3.4.4-rc

If this looks good to you, you can use this as it is. If not, please recreate the branch. So sorry for the trouble.

**Comment by teunbrand** [comment]
> If this looks good to you, you can use this as it is.

Yeah I think it is probably fine, thanks so much for resolving this!

**Comment by yutannihilation** [comment]
@teunbrand 
I see. Thanks for confirming! I'll be more careful next time... Then, I'm closing this pull request in favor of the RC branch.

@thomasp85 
> hmm - can you try to change the target of the PR and see what it will change... I don't think it will bring in all the prior changes, but maybe I'm wrong

I too didn't know what actually would happen, so I created a pull request on my repo, here's how it looks like:

https://github.com/yutannihilation/ggplot2/pull/10

**Pull request closed without merging**
