### PR TITLE
Use sf::sf_project() to transform spatial coordinates.

### LINKED ISSUE #4090: Use sf_project() in function sf_transform_xy()
Per @edzer (https://twitter.com/edzerpebesma/status/1276159543152705543?s=20), `sf::sf_project()` should do what we need and should be faster than the method currently implemented in `sf_transform_xy()` (which generates a list of separate points and then transforms them one by one).

### PR DESCRIPTION
**Pull request by clauswilke**
Closes #4090.

### CODE REVIEW

**Comment by clauswilke** [comment]
@yutannihilation What's the situation with roxygen2 now? I processed documentation with the latest roxygen2 from github and got a ton of changes in numerous `.Rd` files. I didn't commit those here, though.

**Comment by clauswilke** [comment]
Also, the check on R 3.2 complains about an unknown package sf in the checking of cross-references. Is this an issue? Do we still support R 3.2?

**Comment by yutannihilation** [comment]
You need to install `devtools::install_github("r-lib/roxygen2#1109")` as 
https://github.com/r-lib/roxygen2/pull/1109#issuecomment-649466170 is not merged yet.
(I mistakenly wrote `devtools::install_github("r-lib/roxygen2")` on #4062, sorry if you got confused by this)

**Comment by yutannihilation** [comment]
> it seems this is the first time to link to a package that is not available on R 3.2

A small correction. multcomp and Hmisc are such packages, but they doesn't seem to be a problem because they *supposed to* exist on R 3.2, even though they cannot be installed. In the case of sf, as it explicitly requires R >= 3.3, it doesn't exist.

```
❯ checking Rd cross-references ... WARNING
  Packages unavailable to check Rd xrefs: ‘multcomp’, ‘Hmisc’
  Unknown package ‘sf’ in Rd xrefs
```

**Comment by clauswilke** [comment]
The other alternative here would be to just not add a cross reference to the documentation. In any case, I'll merge now, and we can worry about the cross reference later.

**Pull request merged**
