### PR TITLE
Fix typos layer and geom_text docs

### PR DESCRIPTION
**Pull request by collinberke**
I was reading the `geom_text()` docs and came across these minor typos. Feel free to reject or modify any change that goes against the original intent of what was originally written.

Thanks for maintaining this awesome package!

### CODE REVIEW

**Comment by collinberke** [comment]
I just realized I didn't include all the files from `devtools::document()`, since many functions use `@inheritParam layer`. If I need to back this out and resubmit, let me know.

**Comment by teunbrand** [comment]
Hi there, thanks for the PR! It would be nice to regenerate all the relevant docs. I don't think there is a need to back out / resubmit. You could just add a second commit to the same branch and push again, at which point this PR would update with the latest changes.

**Review by thomasp85 — APPROVED** [review]
LGTM

**Comment by thomasp85** [comment]
Thank you!

**Pull request merged**
