### PR TITLE
Improve scales behavior for ordered factors

### PR DESCRIPTION
**Pull request by karawoo**
Related to [1526](https://github.com/tidyverse/ggplot2/issues/1526). Ordered factors and regular factors currently behave pretty much the same, but this is not always appropriate. I've added new ordinal scales for `size`, `alpha`, and `shape` so that

- [x] `scale_shape_ordinal` throws a warning (but `scale_shape_discrete` still does not)
- [x] `scale_size_ordinal` does not throw a warning (but `scale_size_discrete` still does)
- [x] `scale_alpha_ordinal` still does not throw a warning (but `scale_alpha_discrete` does)

Still to do:

- [x] new colour/fill scales for ordinal variables (possibly with viridis)
- [x] test the new behavior

### CODE REVIEW

**Comment by karawoo** [comment]
Some of this could be DRY-er, e.g.

```r
scale_size_ordinal <- function(...) {
  suppressWarnings(scale_size_discrete(...))
}
```

might be better.

**Comment by karawoo** [comment]
If we're going to go with viridis for ordinal scales then we may not need any additional functions, but if not then perhaps something like this should go in the scales package:

```r
seq_ordinal_pal <- function(low, high) {
  function(n) {
    v <- seq(0, 1, length.out = n)
    scales::colour_ramp(c(low, high))(v)  
  }
}
```

Then `scale_colour_ordinal` would be:

```r
scale_colour_ordinal <- function(..., low = "#132B43", high = "#56B1F7",
                                 na.value = "grey50") {
  discrete_scale(
    "colour",
    "sequence",
    seq_ordinal_pal(low, high),
    na.value = na.value,
    ...
    )
}
```

which produces output like this:

```r
d <- diamonds[sample(nrow(diamonds), 1000), ]

ggplot(d, aes(carat, price)) +
  geom_point(aes(colour = cut))
```

diamonds

**Comment by has2k1** [comment]
You need to be careful (or document the aberrations), depending on how you interpolate between the high and low colours of a colourmap, not all generated colours may be part of the continuous version of the colourmap. 

This will definitely affect colourmaps that aim to perceptually-uniform, like viridis.

**Comment by karawoo** [comment]
@hadley GitHub isn't letting me request a review but can you tell me what you think of this? I can't remember if we decided on Monday what to do about the ordinal color scales.

**Comment by hadley** [comment]
Looks good so far. We should make a decision about ordinal colour scales too. Using viridis seems like a reasonable choice to me.

**Comment by karawoo** [comment]
Trying @jennybc's edits from #2189 in this PR to see if it makes codecov chill out.

**Comment by karawoo** [comment]
Using viridis sounds good to me, so once #2178 gets merged I can add that here.

**Comment by karawoo** [comment]
I removed Jenny's codecov-related commits and added `scale_fill_ordinal` and `scale_colour_ordinal`, which both default to viridis.

**Comment by karawoo** [comment]
@hadley one quick question before I merge -- since we're making viridis the default for ordered factors, should `viridisLite` go in Imports rather than Suggests?

**Comment by hadley** [comment]
Yes!

**Pull request merged**
