### PR TITLE
Update r4ds url

### PR DESCRIPTION
**Pull request by zekiakyol**
- This pull request updates r4ds(<https://r4ds.had.co.nz/>) to r4ds 2e (https://r4ds.hadley.nz/) on the package website.

### CODE REVIEW

**Comment by teunbrand** [comment]
Thanks for the PR! Is there any chance I could convince you to run `devtools::build_readme()` to propagate changes from the `.Rmd` file to the `.md` file? If git flags changes in the .png images, it should be safe to not commit these, as they may be platform dependent.

**Comment by zekiakyol** [comment]
You are welcome!
When I run `devtools::build_readme()` git flags a change in **man\figures\README-example-1.png**.
I think it is safer to close this pull request without merging.

**Comment by teunbrand** [comment]
> I think it is safer to close this pull request without merging.

The PR is good, but the changes need to be propagated to the `.md` file. You can just not commit the change in the `.png` file.

**Review by teunbrand — APPROVED** [review]
Looks good to me, thanks for the PR!

**Comment by zekiakyol** [comment]
You are welcome!

**Pull request merged**
