### PR TITLE
Fixing documentation in binned_scale suggesting it defaults to oob = censor

### PR DESCRIPTION
**Pull request by joshhwuu**
Attempting to resolve issue #5655

### CODE REVIEW

**Comment by teunbrand** [comment]
Hi there, thanks for putting together a PR. The documentation is generated from the .R files, so the appropriate place to make edits is here: https://github.com/tidyverse/ggplot2/blob/a4be39dee07010c67c31ace059b1f0a24129fc65/R/scale-.R#L249-L266

After such edits have been made, you can use `devtools::document()` to regenerate the .Rd files.

**Comment by joshhwuu** [comment]
When I was using roxygen2::roxygenise(), it automatically remade the .Rd files for a lot of the R files, including aes_colour_fill_alpha.Rd, position_dodge.Rd, etc. These changes seem to be minimal in every file except man/binned_scale.Rd,  man/scale_binned.Rd and man/scale_steps.Rd. 

For example, in man/aes_colour_fill_alpha.Rd:

image

It seems that document() simply reordered two of the items so all items are alphabetical, and the same goes for some of the other minimally-changed files.

Should I revert the changes to these minimally-changed documents and then push again or is it okay to leave them in?

**Comment by teunbrand** [comment]
The unrelated changes are due to roxygen2 versions and is nothing to worry about. We'll merge in another PR soon that updates these files too, and they shouldn't show up as diffs anymore. I'm going to hold off on merging this PR until release, to avoid conflicts, but I think the PR looks great as-is.

**Review by teunbrand — APPROVED** [review]
Looks good to me!

**Pull request merged**
