### PR TITLE
Complete list of built-in transformations derived from scales::name_trans

### PR DESCRIPTION
**Pull request by Henrik-P**

### CODE REVIEW

**Comment by yutannihilation** [comment]
Thanks, could you update the docs by running `devtools::document()`?

**Comment by Henrik-P** [comment]
Sorry, I'm not familiar with the `devtools::document()` procedure. When searching I ended up here: [The documentation workflow](http://r-pkgs.had.co.nz/man.html). Have I understood it correctly that I start by saving a hard copy of the "scale-.r" file, then render it in RStudio `devtools::document()`?

**Comment by yutannihilation** [comment]
> Have I understood it correctly that I start by saving a hard copy of the "scale-.r" file, 

No. How did you make this pull request? (I'm happy to generate the docs for you, but I want to help you if possible.)

**Comment by Henrik-P** [comment]
>How did you make this pull request?

I have a ggplot repository "Forked from tidyverse/ggplot2". I made the relevant changes there in "scale-.r", [Compare changes](https://github.com/tidyverse/ggplot2/compare) / compare across forks, select my repository as 'head repository', 'Create pull request'.

Sorry for my ignorance.

**Comment by yutannihilation** [comment]
No need to feel sorry!

Thanks for the details. It seems you need to get familiar with git and RStudio (or some other tools) a bit more, so let me do `devtools::document()` this time. You could

1. clone your ggplot2 repo in your local
2. run `devtools::document()` on the root directory of ggplot2
3. commit the changes
4. push to GitHub

c.f. https://happygitwithr.com/rstudio-git-github.html#clone-the-new-github-repository-to-your-computer-via-rstudio

**Comment by yutannihilation** [comment]
Thanks for your contribution 👍

**Comment by Henrik-P** [comment]
Thanks for your kind words and for pointing me to relevant git docs.

**Pull request merged**
