### PR TITLE
Implement new coord_mirror() and theme_rtl() for RtL plotting

### PR DESCRIPTION
**Pull request by dpseidel**
This PR is a WIP. Inspired by [this article](http://rnotr.com/ggplot/plotly/arabic-plots/), I have begun playing around with how to implement RtL plotting in ggplot2. Though there seems to be some debate about what is a [correct](https://www.quora.com/In-right-to-left-languages-are-chart-axes-drawn-differently) [implementation](https://ux.stackexchange.com/questions/42895/right-to-left-graph-labels-for-right-to-left-languages) of RtL axes and it seems many RtL languages plot LtR anyhow, I think the functionality is really neat and ggplot2 should consider adding features that make it possible for the audiences that would use it. In that vein.... 

Currently this implementation was really quite simple.  I simply adapted `coord_flip()` to create a new `coord_mirror()` and then added a new `theme_rtl()`. This doesn't yet deal with the text encoding issue mentioned in the original article but as they note much of that is OS specific so possibly/probably outside the scope of ggplot2. 

As currently implemented, a RtL plot requires 3 specifications: the new theme, the new coord, and (at least for continuous data) `scale_x_reverse()`. I wonder if there is a better way to go about this or a way to bundle these three elements together in some sort of default. Example below:
``` r
library(ggplot2)
library(tibble)
df <- tibble(x = 1:10, y = 1:10, z = rep(c("A", "B"), 5))
ggplot(df, aes(x, y, col = z)) + 
  geom_point() + 
  coord_mirror() + 
  theme_rtl() + 
  scale_x_reverse() +
  ggtitle("Right Aligned Title")
```

``` r

df2 <- tibble(x = letters[1:10], y = 1:10, z = rep(c("A", "B"), 5))
ggplot(df2, aes(x, y, col = z)) + 
  geom_point() + 
  coord_mirror() + 
  theme_rtl() +
  ggtitle("Right Aligned Title")
```

@isteves has been super helpful in thinking about this, and may have some opinions to add to any discussion or iteration so I'm tagging her here.

### CODE REVIEW

**Comment by clauswilke** [comment]
I would expect a `coord_mirror()` to reverse the x axis.

**Comment by dpseidel** [comment]
@clauswilke certainly it could be implemented that way. The plot I was original trying to replicate, from the article linked above, did not flip the x axis (they were plotting a discrete variable) which is why I left it the way I did, but you're right that's an easier implementation.

**Comment by clauswilke** [comment]
I think all you need to do is add the following function to your `CoordMirror()`:
``` r
  setup_panel_params = function(self, scale_x, scale_y, params = list()) {
    params <- ggproto_parent(CoordCartesian, self)$setup_panel_params(scale_x, scale_y, params)
    
    params$x.range <- rev(params$x.range)
    params$x.labels <- rev(params$x.labels)
    params
  }
```
And it seems to works with discrete and continuous scales. I would assume in right-to-left writing the first letter in the alphabet is shown in the right-most position, which this addition to the coord achieves.

**Comment by dpseidel** [comment]
Great! Thanks for the quick code @clauswilke! It's mplemented now and things actually *mirror* as you would expect without the `scale_x_reverse()` call.  

``` r
library(ggplot2)
library(tibble)
df <- tibble(x = 1:10, y = 1:10, z = rep(c("A", "B"), 5))
ggplot(df, aes(x, y, col = z)) +
  geom_point() +
  coord_mirror() +
  theme_rtl() +
  ggtitle("Right Aligned Title")
```



``` r

df2 <- tibble(x = letters[1:10], y = 1:10, z = rep(c("A", "B"), 5))
ggplot(df2, aes(x, y, col = z)) +
  geom_point() +
  coord_mirror() +
  theme_rtl() +
  ggtitle("Right Aligned Title")
```



Created on 2018-08-09 by the [reprex
package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by clauswilke** [comment]
Another point: Maybe make `theme_rtl()` not a complete theme so it can be combined with other themes. I.e., something like:
``` r
theme_rtl <- function() {
  theme(
    legend.position = "left",
    plot.title = element_text(hjust = 1)
  )
}
```
(Maybe there's a better name for the function, though, so it sounds like a verb and not a noun. Maybe `make_theme_rtl()` or `reverse_theme()`.)

**Comment by isteves** [comment]
Hi all, I don't have anything technical to contribute to this discussion, but I'd like to summarize my investigation into RTL graphs here (@dpseidel has already heard much of this).  

I'm of the camp that RTL graphs with _continuous_ axes should not be encouraged.  (In my mind, it's a bit like all agreeing to the metric system and then deciding to switch _back_ into non-standard units.)  Mathematics has a standard convention with regards to axes, and I think we should stick with it.

## Conversations with people familiar with RTL languages

- Iranian lady (psychology PhD) that I met in a hostel - graphs are always LTR, tables are RTL. Math is LTR
- Pakistani taxi driver (Aamer) - both RTL/LTR are taught in schools, depending on which language (Urdu/English) is being used
- Israeli friend 1: "I did it only once or twice. It is rare in papers that I saw."
- Israeli friend 2: "I also hate RTL in this context, and changed it for my school pupils when they gave me such figures." (note: this is what Excel defaults to for RTL languages)
- East Asian studies PhD: In China, writing is almost always LTR.  In Taiwan, it's still mixed.  You can get writing that is RTL/LTR/up-to-down, but _typically_ horizontal writing is now LTR and vertical writing is RTL.  Regardless, all graphs are LTR.

## Online graph search

I found it surprisingly difficult to search for graphs in RTL languages, but I hit on a few methods that seem to work ok:

- Google Image search "stock market" or "growth" or "statistics" - I used Google Translate to get words in Arabic/Hebrew/Persian/Urdu for my searches.  The vast majority of the results seemed to be LTR.
    - Stock market: [Arabic](https://www.google.com/search?biw=1163&bih=594&tbm=isch&sa=1&ei=OsBtW-CYIcyKtQXa_oHoCg&q=%D8%B3%D9%88%D9%82+%D8%A7%D9%84%D8%A3%D9%88%D8%B1%D8%A7%D9%82+%D8%A7%D9%84%D9%85%D8%A7%D9%84%D9%8A%D8%A9&oq=%D8%B3%D9%88%D9%82+%D8%A7%D9%84%D8%A3%D9%88%D8%B1%D8%A7%D9%82+%D8%A7%D9%84%D9%85%D8%A7%D9%84%D9%8A%D8%A9&gs_l=img.3...59442.59442.0.59809.1.1.0.0.0.0.0.0..0.0....0...1c.1.64.img..1.0.0....0.rH0f8wPtT6c) [Hebrew](https://www.google.com/search?biw=1163&bih=594&tbm=isch&sa=1&ei=d8BtW_SABIaIsQX78KTADw&q=%D7%91%D7%95%D7%A8%D7%A1%D7%94&oq=%D7%91%D7%95%D7%A8%D7%A1%D7%94&gs_l=img.3..0l4j0i30k1l5j0i24k1.22464.22464.0.22755.1.1.0.0.0.0.110.110.0j1.1.0....0...1c.1.64.img..0.1.109....0.XhNG385Um2A) [Persian](https://www.google.com/search?biw=1163&bih=594&tbm=isch&sa=1&ei=p8BtW--dCIT-tAXkrZCwDw&q=%D8%A8%D8%A7%D8%B2%D8%A7%D8%B1+%D8%B3%D9%87%D8%A7%D9%85&oq=%D8%A8%D8%A7%D8%B2%D8%A7%D8%B1+%D8%B3%D9%87%D8%A7%D9%85&gs_l=img.3..0j0i24k1l5.41919.41919.0.42343.1.1.0.0.0.0.114.114.0j1.1.0....0...1c.1.64.img..0.1.113....0.oyxMo0BeRyI) [Urdu](https://www.google.com/search?biw=1163&bih=594&tbm=isch&sa=1&ei=jsBtW5_HJpHUsAXPyZWQBw&q=%D8%A7%D8%B3%D9%B9%D8%A7%DA%A9+%D9%85%D8%A7%D8%B1%DA%A9%DB%8C%D9%B9&oq=%D8%A7%D8%B3%D9%B9%D8%A7%DA%A9+%D9%85%D8%A7%D8%B1%DA%A9%DB%8C%D9%B9&gs_l=img.3...23074.23074.0.23799.1.1.0.0.0.0.109.109.0j1.1.0....0...1c.1.64.img..0.0.0....0.7wTs88uGvEs)
    - Growth: [Arabic](https://www.google.com/search?biw=1163&bih=594&tbm=isch&sa=1&ei=J8BtW6eKN4X4tAX7tKD4Dg&q=%D9%86%D9%85%D9%88&oq=%D9%86%D9%85%D9%88&gs_l=img.3..0l10.17439.17439.0.17767.1.1.0.0.0.0.119.119.0j1.1.0....0...1c.1.64.img..0.1.117....0.5S8swg5vt3w) [Hebrew](https://www.google.com/search?biw=1163&bih=594&tbm=isch&sa=1&ei=CcJtW6jwK47msAXJ1rKoBg&q=%D7%A6%D7%9E%D7%99%D7%97%D7%94&oq=%D7%A6%D7%9E%D7%99%D7%97%D7%94&gs_l=img.3..0l2j0i30k1l8.37833.37833.0.38179.1.1.0.0.0.0.122.122.0j1.1.0....0...1c.1.64.img..0.1.121....0.elFH2-Wi_p4) [Persian](https://www.google.com/search?biw=1163&bih=594&tbm=isch&sa=1&ei=0sBtW6GqEYz2tAW6zKioDQ&q=%D8%B1%D8%B4%D8%AF&oq=%D8%B1%D8%B4%D8%AF&gs_l=img.3..0l10.32183.32183.0.32515.1.1.0.0.0.0.111.111.0j1.1.0....0...1c.1.64.img..0.1.110....0.JDGzLcSvP0k) (Urdu gave strange results to this)
   - Statistics: [Arabic](https://www.google.com/search?biw=1163&bih=594&tbm=isch&sa=1&ei=9MFtW87KM4PatQWf0ajgBQ&q=%D8%A7%D9%84%D8%A5%D8%AD%D8%B5%D8%A7%D8%A1&oq=%D8%A7%D9%84%D8%A5%D8%AD%D8%B5%D8%A7%D8%A1&gs_l=img.3..0j0i30k1j0i5i30k1l3j0i24k1l4.19628.19628.0.20048.1.1.0.0.0.0.143.143.0j1.1.0....0...1c.1.64.img..0.1.141....0._ILdBY8-y08) [Hebrew](https://www.google.com/search?biw=1163&bih=594&tbm=isch&sa=1&ei=0MFtW4yAKYW6tQX1gq7ICQ&q=%D7%A1%D7%98%D7%98%D7%99%D7%A1%D7%98%D7%99%D7%A7%D7%94&oq=%D7%A1%D7%98%D7%98%D7%99%D7%A1%D7%98%D7%99%D7%A7%D7%94&gs_l=img.3..0j0i30k1l4j0i5i30k1l5.35220.35220.0.35483.1.1.0.0.0.0.124.124.0j1.1.0....0...1c.1.64.img..0.1.122....0.SjiYxMIRvzM) [Persian](https://www.google.com/search?biw=1163&bih=594&tbm=isch&sa=1&ei=88BtW6itIcHEsAWexqKgDw&q=%D8%A2%D9%85%D8%A7%D8%B1&oq=%D8%A2%D9%85%D8%A7%D8%B1&gs_l=img.3..0l10.183311.183311.0.183657.1.1.0.0.0.0.135.135.0j1.1.0....0...1c.1.64.img..0.1.134....0.fQAgY712IVs) [Urdu](https://www.google.com/search?biw=1163&bih=594&tbm=isch&sa=1&ei=rMFtW79kiZCwBf6TjZAK&q=%D8%A7%D8%B9%D8%AF%D8%A7%D8%AF+%D9%88+%D8%B4%D9%85%D8%A7%D8%B1&oq=%D8%A7%D8%B9%D8%AF%D8%A7%D8%AF+%D9%88+%D8%B4%D9%85%D8%A7%D8%B1&gs_l=img.3..0i8i30k1.15971.15971.0.16987.1.1.0.0.0.0.101.101.0j1.1.0....0...1c.1.64.img..0.1.101....0.PgtUfP4uyzk)
- Google Scholar search.  I tried a similar tactic with Google scholar, but it was a bit more difficult because graphs are hidden in PDFs.  *_Note:_ the place of origin are educated guesses based on the URL but may be wrong 
    - Iran: [example 1](http://journals-old.modares.ac.ir/article_1447_5d83ace058caad4edd248eb5d3b385d6.pdf) [example 2](http://www.sid.ir/fa/journal/frmCreport.aspx)
    - Iraq: [example 1](http://www.uokufa.edu.iq/journals/index.php/kjas/article/view/3818/3119) [example 2](https://www.iasj.net/iasj?func=fulltext&aId=40493)
    - Israel: Most of the papers that came up were locked behind JSTOR, so I didn't bother with them.  My friend sent me newspaper photos instead (from Haaretz):

downloads

**Comment by adisarid** [comment]
I'm with @isteves on this one. The mathematical convention of left to right usually remains even when the language is RTL (at least from my perspective as a native Hebrew speaker).

The only real thing that is truly needed in terms of RTL charts is not actually covered in this pull request. This is the direction of text. I.e., if you have punctuation marks in the text they will appear at the wrong side. `hjust` controls the text alignment but not the text direction. See the stackoverflow question I posted [here](https://stackoverflow.com/questions/53915070/in-ggplot2-how-do-i-adjust-the-direction-of-text-direction-not-alignment?noredirect=1#comment94673697_53915070).

**Comment by clauswilke** [comment]
@adisarid This is of interest to me, as I'm planning to improve text handling in ggplot2. How does right-to-left text usually work? Is it reasonable to assume that layouting works just like left-to-right only in the other direction, or are there additional issues? And what are the conventions for mixed text? It seems to get complicated pretty quickly.

**Comment by adisarid** [comment]
@clauswilke - good question.
Apparently, my stackoverflow question, which is a simpler version to what you are asking, was answered, and it's not that complicated as I thought. All I needed was a unicode explicit directional embedding `paste("\u202B", "זה טקסט בעברית!")` and that tells the device to render the text RTL [(see Henrik's answer)](https://stackoverflow.com/questions/53915070/in-ggplot2-how-do-i-adjust-the-direction-of-text-direction-not-alignment). The `!` would go in the right place (which is opposite to how this markdown is rendered).

To implement this in `element_text`, I guess the simplest thing would be to add a flag parameter which does this, i.e., `element_text(directionRTL = TRUE)`, and then the element's text gets concatenated with this directional character.

For mixed text, e.g. English with Hebrew/Arabic. It's indeed more complicated, because you have to guess when an English word is meant to end a Hebrew sentence or start a new English sentence.
We would have to use a smart parser which goes over the original text and when it detects a Hebrew/Arabic character set it wraps it with `\u202B` and ends it with `\u202A`. These wrappers would have to include punctuation marks which end sentences (so characters like `.?!- ` need to be interpreted either as English or as Hebrew/Arabic, depending on context). The decision about including or excluding English words within the unicode wrappers would have to be decided based on if that English word was preceded by a stop-sentence punctuation (i.e., `!.?`) would exclude the word from the RTL command, but not things like `:- `.

Makes sense?

**Comment by certara-smouksassi** [comment]
One issue in these languages ( at least in arabic) is that you might have separate rules for numerals:
https://www.w3.org/TR/alreq/#h_numbers 
https://www.vengaglobal.com/blog/bi-directional-languages-arabic-hebrew-farsi/

**Comment by thomasp85** [comment]
@dpseidel what is the status of this PR?

**Comment by dpseidel** [comment]
It's functional and pretty close to finished, just needs a few visual tests. I agree it could be nice to make it an incomplete theme as suggested by @clauswilke.  

It begin as simple curiosity during my internship. Ultimately it stalled because it wasn't clear if there was consensus on exactly how and when RtL plotting is used in the wild and thus, how it should be it should be implemented in ggplot2, if at all. @hadley, what do you think? Is this a feature you'd still like to see in ggplot2?

If we decide it's worth considering further I'm happy to finish it off either in time for 3.2 or for a release down the road a bit.

**Comment by hadley** [comment]
I think it's worth finishing off by making it a partial theme, and removing the x-axis mirroring.

**Comment by dpseidel** [comment]
Alright, I have reverted the x-axis mirroring, converted `theme_rtl` to a partial theme, and added a visual test. Since it was no longer a complete theme, I gave it it's own documentation but left it in the theme-default.r file.

**Comment by thomasp85** [comment]
We are closing this. It appears that only the titles should be right-aligned in an rtf theme which is so easy to change that the addition of a new theme seems overkill. Work on supporting correctly rendered non-western scripts (e.g. Arabic, Urdu, Hebraic) continues in ragg and textshaper

**Pull request closed without merging**
