### PR TITLE
Consolidate scale definition of position aesthetics

### LINKED ISSUE #3342: Consolidate definition of position aesthetics
In attempting to refactor the guide code to work with position guides, I found 8 definitions of  what is a position aesthetic, only one of which is used by `is_position_aes()`.

https://github.com/tidyverse/ggplot2/blob/1f6f0cb4462aa9e3b5f51dc7fd594073e78351da/R/aes.r#L176-L177

https://github.com/tidyverse/ggplot2/blob/1f6f0cb4462aa9e3b5f51dc7fd594073e78351da/R/scale-continuous.r#L83

https://github.com/tidyverse/ggplot2/blob/1f6f0cb4462aa9e3b5f51dc7fd594073e78351da/R/scale-continuous.r#L102

https://github.com/tidyverse/ggplot2/blob/1f6f0cb4462aa9e3b5f51dc7fd594073e78351da/R/scale-discrete-.r#L63

https://github.com/tidyverse/ggplot2/blob/1f6f0cb4462aa9e3b5f51dc7fd594073e78351da/R/scale-discrete-.r#L54

https://github.com/tidyverse/ggplot2/blob/1f6f0cb4462aa9e3b5f51dc7fd594073e78351da/R/annotation.r#L42-L43

https://github.com/tidyverse/ggplot2/blob/1f6f0cb4462aa9e3b5f51dc7fd594073e78351da/R/scale-date.r#L142

https://github.com/tidyverse/ggplot2/blob/1f6f0cb4462aa9e3b5f51dc7fd594073e78351da/R/scale-date.r#L179

https://github.com/tidyverse/ggplot2/blob/1f6f0cb4462aa9e3b5f51dc7fd594073e78351da/R/scale-date.r#L291

Is there a reason that any of these definitions should be different from the one in `scale_(x|y)_continuous()`?

### LINKED ISSUE #4966: geom_vline() does not extend the limits if the axis is a Date
Hi,

When using a date axis, `geom_vline()` will only show if there is data nearby the intercept.
For numeric axes though (y in my example below), if the intercept is off-limit, the plot will extend to show the line, which is the expected behavior.

``` r
library(tidyverse)
library(lubridate)

set.seed(1234)
df = tibble(
  x = as.Date(0:19, origin=ymd("2022-01-01")), 
  y=rnorm(20)
)
df %>% 
  ggplot(aes(x,y)) + 
  geom_point() + 
  geom_hline(yintercept=5) +                 #will show (extends)
  geom_vline(xintercept=ymd("2022-01-10")) + #will show (within limits)
  geom_vline(xintercept=ymd("2022-03-01")) + #will not show (off-limit without extension)
```

<sup>Created on 2022-08-25 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

<details style="margin-bottom:10px;">
<summary>
Session info
</summary>

``` r
sessionInfo()
#> R version 4.2.1 (2022-06-23 ucrt)
#> Platform: x86_64-w64-mingw32/x64 (64-bit)
#> Running under: Windows 10 x64 (build 14393)
#> 
#> Matrix products: default
#> 
#> locale:
#> [1] LC_COLLATE=French_France.1252  LC_CTYPE=French_France.1252   
#> [3] LC_MONETARY=French_France.1252 LC_NUMERIC=C                  
#> [5] LC_TIME=French_France.1252    
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> other attached packages:
#>  [1] lubridate_1.8.0 forcats_0.5.2   stringr_1.4.1   dplyr_1.0.9    
#>  [5] purrr_0.3.4     readr_2.1.2     tidyr_1.2.0     tibble_3.1.8   
#>  [9] ggplot2_3.3.6   tidyverse_1.3.2
#> 
#> loaded via a namespace (and not attached):
#>  [1] assertthat_0.2.1    digest_0.6.29       utf8_1.2.2         
#>  [4] mime_0.12           R6_2.5.1            cellranger_1.1.0   
#>  [7] backports_1.4.1     reprex_2.0.2        evaluate_0.16      
#> [10] httr_1.4.4          highr_0.9           pillar_1.8.1       
#> [13] rlang_1.0.4         curl_4.3.2          googlesheets4_1.0.1
#> [16] readxl_1.4.1        rstudioapi_0.14     R.utils_2.12.0     
#> [19] R.oo_1.25.0         rmarkdown_2.16      styler_1.7.0       
#> [22] labeling_0.4.2      googledrive_2.0.0   munsell_0.5.0      
#> [25] broom_1.0.0         compiler_4.2.1      modelr_0.1.9       
#> [28] xfun_0.32           pkgconfig_2.0.3     htmltools_0.5.3    
#> [31] tidyselect_1.1.2    fansi_1.0.3         crayon_1.5.1       
#> [34] tzdb_0.3.0          dbplyr_2.2.1        withr_2.5.0        
#> [37] R.methodsS3_1.8.2   grid_4.2.1          jsonlite_1.8.0     
#> [40] gtable_0.3.0        lifecycle_1.0.1     DBI_1.1.3          
#> [43] magrittr_2.0.3      scales_1.2.1        cli_3.3.0          
#> [46] stringi_1.7.8       farver_2.1.1        fs_1.5.2           
#> [49] xml2_1.3.3          ellipsis_0.3.2      generics_0.1.3     
#> [52] vctrs_0.4.1         tools_4.2.1         R.cache_0.16.0     
#> [55] glue_1.6.2          hms_1.1.2           fastmap_1.1.0      
#> [58] yaml_2.3.5          colorspace_2.0-3    gargle_1.2.0       
#> [61] rvest_1.0.3         knitr_1.40          haven_2.5.1
```

</details>

A workaround would be to add `geom_blank(aes(x=ymd("2022-03-01")))` but it feels a bit unnecessary.

### PR DESCRIPTION
**Pull request by teunbrand**
This PR aims to fix #3342 and fix #4966.

Briefly, all position scales now use the definitions of x- and y-aesthetics from the `gglobal_global` environment.
This ensures that rarer position aesthetics, like `xintercept`, contribute to the scale limits and are transformed by the scale.

I have been [forewarned](https://github.com/tidyverse/ggplot2/issues/4966#issuecomment-1341594007) that this might lead to unexpected issues, but I don't foresee any at the moment. It might lead to some visual changes, but I'd argue they might be intended.

Reprex from #4966:

``` r
devtools::load_all("~/packages/ggplot2/")
#> ℹ Loading ggplot2
library(lubridate)

set.seed(1234)
df = tibble(
  x = as.Date(0:19, origin = ymd("2022-01-01")), 
  y = rnorm(20)
)
df |>
  ggplot(aes(x, y)) + 
  geom_point() + 
  geom_hline(yintercept = 5) +                 
  geom_vline(xintercept = ymd("2022-01-10")) +
  geom_vline(xintercept = ymd("2022-03-01"))
```

<sup>Created on 2024-01-12 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

### CODE REVIEW

**Comment by michaelgrund** [comment]
Are there any plans to put the solution regarding this issue into the next release? It's really annoying that vertical lines plotted far outside the date limits are not considered.

**Comment by teunbrand** [comment]
> It's really annoying that vertical lines plotted far outside the date limits are not considered.

I totally agree with you there.

We want the next release to be a low-risk hotfix where we mostly fix mistakes from 3.5.0 and not put in something disruptive.
This PR has a non-zero risk of breaking the assumption of some packages that depend on ggplot2, so I think it'd be wise to postpone this a little bit further (or run revdepcheck for this PR). Any thoughts @thomasp85?

**Comment by thomasp85** [comment]
yes, this will be postponed

**Comment by thomasp85** [comment]
After a lot of digging I found that the addition of `"intercept"` to the list of positional aesthetics was the cause of the troubles I remembered. Since this is not touched here I think it's safe. Will run revdepcheck regardless

**Comment by thomasp85** [comment]
Bunch of revue-check failures. I'm pretty sure that most or all are unrelated to this but please sift through them

**Comment by teunbrand** [comment]
I can see the irony in some of the revdep failures.
Basically, people have found workarounds for the problem that date scales don't accept `{x/y}intercept` aesthetics.
However, this PR now breaks those workarounds by making it easier.

For example this now correctly throws the error that it will not accept any non-dates.

``` r
devtools::load_all("~/packages/ggplot2/")
#> ℹ Loading ggplot2

# Analogous to current workarounds
ggplot(economics, aes(date, unemploy)) +
  geom_line() +
  geom_vline(xintercept = as.numeric(as.Date("1983-01-31")))
#> Error in `transformation$transform()` at ggplot2/R/scale-.R:628:3:
#> ! `transform_date()` works with objects of class <Date> only
```

Whereas now the solution is to simply drop the `as.numeric()` workaround.

```r
ggplot(economics, aes(date, unemploy)) +
  geom_line() +
  geom_vline(xintercept = as.Date("1983-01-31"))
```



<sup>Created on 2024-05-21 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by teunbrand** [comment]
TODO: try to catch these situations, convert to numeric with warning

**Comment by teunbrand** [comment]
Numeric input now throws warnings instead of errors:

``` r
devtools::load_all("~/packages/ggplot2")
#> ℹ Loading ggplot2

ggplot(economics, aes(date, unemploy)) +
  geom_line() +
  geom_vline(xintercept = as.numeric(as.Date("1983-01-31")))
#> Warning in scale_x_date(): A <numeric> value was passed to a Date scale.
#> ℹ The value was converted to a <Date> object.

ggplot(economics, aes(as.POSIXct(date), unemploy)) +
  geom_line() +
  geom_vline(xintercept = as.numeric(as.POSIXct("1983-01-31")))
#> Warning in scale_x_datetime(): A <numeric> value was passed to a Datetime scale.
#> ℹ The value was converted to a <POSIXt/POSIXct> object.
```

<sup>Created on 2024-06-04 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Review by thomasp85 — APPROVED** [review]
LGTM 🤞

**Pull request merged**
