### PR TITLE
Update tidy eval reexport file

### PR DESCRIPTION
**Pull request by lionel-**
New template from usethis.

The main changes are to export `as_label()` and `as_name()`, and to undocument stuff that should no longer be exported, but that we keep exporting for compatibility (`enexpr()`, `quo()`, `quo_name()`, etc).

### CODE REVIEW

**Comment by yutannihilation** [comment]
Probably, this version requirement needs to be tightened to 3.1.

https://github.com/tidyverse/ggplot2/blob/3b691727fffa7d3bbaf7d80b70600aa72eb13efd/DESCRIPTION#L30

**Comment by lionel-** [comment]
I'm about to send a PR for 3.1, currently being checked on travis: https://travis-ci.org/tidyverse/ggplot2/builds/529211641

**Comment by yutannihilation** [comment]
Aw, sorry, I meant 0.3.1, the version of rlang when `as_name()` and `as_label()` were introduced.

**Comment by lionel-** [comment]
> Aw, sorry, I meant 0.3.1, the version of rlang when as_name() and as_label() were introduced.

ah yes good point!

**Comment by hadley** [comment]
I'm worried that this might cause revdep failures (because of namespace conflicts, which are common with ggplot2 revdeps), so I think we should wait until the next version for this.

**Comment by thomasp85** [comment]
@Hadley are we good to go on this now?

**Comment by hadley** [comment]
I think we probably need to reconsider this completely now. I suspect `expr(), `enquo()`, `enquos()`, `sym()`, and `syms()` can now be considered advanced usage any only `:=` and `.data` really need to be exported. But I think we need to have that discussion elsewhere, so I'd recommend closing this PR. (But you should bump the R version requirement to be consistent with the rest of the tidyverse)

**Comment by yutannihilation** [comment]
We bumped already in https://github.com/tidyverse/ggplot2/pull/3309

**Pull request closed without merging**
