### PR TITLE
updated revdeps

### PR DESCRIPTION
**Pull request by topepo**
[database file](https://www.dropbox.com/s/llilyu97detb5xv/data.sqlite?dl=0)

We checked 2622 reverse dependencies (2212 from CRAN + 410 from BioConductor), comparing R CMD check results across CRAN and dev versions of this package.

 * We saw 30 new problems
 * We failed to check 70 packages

Issues with CRAN packages are summarised below.

### New problems
(This reports the first line of each new failure)

* bayesAB
  checking examples ... ERROR

* breathteststan
  checking examples ... ERROR

* CSTools
  checking tests ...

* esmisc
  checking examples ... ERROR

* fergm
  checking examples ... ERROR

* fingertipscharts
  checking examples ... ERROR
  checking tests ...

* ggalt
  checking whether package ‘ggalt’ can be installed ... WARNING

* ggforce
  checking whether package ‘ggforce’ can be installed ... WARNING

* ggpol
  checking whether package ‘ggpol’ can be installed ... WARNING

* ggpolypath
  checking whether package ‘ggpolypath’ can be installed ... WARNING

* ggsolvencyii
  checking whether package ‘ggsolvencyii’ can be installed ... WARNING

* ggspatial
  checking whether package ‘ggspatial’ can be installed ... WARNING

* ggstance
  checking tests ...

* ggstatsplot
  checking tests ...

* ggtern
  checking whether package ‘ggtern’ can be installed ... WARNING

* heatmaply
  checking installed package size ... NOTE

* HistDAWass
  checking examples ... ERROR

* incR
  checking examples ... ERROR

* interflex
  checking examples ... ERROR

* jcolors
  checking examples ... ERROR

* lime
  checking tests ...

* mlr
  checking examples ... ERROR

* MTLR
  checking tests ...

* SCORPIUS
  checking tests ...

* shiny
  checking tests ...

* ssMousetrack
  checking installed package size ... NOTE
  checking for GNU extensions in Makefiles ... NOTE

* stats19
  checking tests ...

* trialr
  checking installed package size ... NOTE
  checking dependencies in R code ... NOTE
  checking for GNU extensions in Makefiles ... NOTE

* vdiffr
  checking tests ...

* xpose
  checking examples ... ERROR
  checking tests ...

### Failed to check

* aslib                  (NA)
* BACA                   (NA)
* BACCT                  (NA)
* bamdit                 (NA)
* BayesRS                (NA)
* BNSP                   (NA)
* BPEC                   (NA)
* bsam                   (NA)
* BTSPAS                 (NA)
* CaliCo                 (NA)
* CollapsABEL            (NA)
* colorednoise           (NA)
* crmPack                (NA)
* Crossover              (NA)
* Deducer                (NA)
* DeLorean               (NA)
* DiversityOccupancy     (NA)
* dynfrail               (NA)
* dynr                   (NA)
* evoper                 (NA)
* ewoc                   (NA)
* fingerPro              (NA)
* fsdaR                  (NA)
* G2Sd                   (NA)
* gastempt               (NA)
* imageData              (NA)
* imbalance              (NA)
* InSilicoVA             (NA)
* jarbes                 (NA)
* joineRML               (NA)
* JointAI                (NA)
* likeLTD                (NA)
* lilikoi                (NA)
* llama                  (NA)
* LLSR                   (NA)
* matchingMarkets        (NA)
* mbgraphic              (NA)
* mcmcabn                (NA)
* mleap                  (NA)
* morse                  (NA)
* mwaved                 (NA)
* NPflow                 (NA)
* OpenStreetMap          (NA)
* openVA                 (NA)
* petro.One              (NA)
* phase1PRMD             (NA)
* phase1RMD              (NA)
* pimeta                 (NA)
* poppr                  (NA)
* PortfolioEffectHFT     (NA)
* qdap                   (NA)
* RcmdrPlugin.FuzzyClust (NA)
* Rdrools                (NA)
* rmcfs                  (NA)
* robustHD               (NA)
* rpanel                 (NA)
* rpf                    (NA)
* rrepast                (NA)
* RSCAT                  (NA)
* rstanarm               (NA)
* rsvg                   (NA)
* RtutoR                 (NA)
* SeqFeatR               (NA)
* simmr                  (NA)
* sitmo                  (NA)
* spcosa                 (NA)
* TeachingDemos          (NA)
* vortexR                (NA)
* XLConnect              (NA)
* zooaRchGUI             (NA)

### CODE REVIEW

**Comment by thomasp85** [comment]
@paleolimbot can you begin to go through the list of problems and group them into the same apparent root cause. After that we can begin to tackle the issues one by one

**Comment by thomasp85** [comment]
Let’s just keep it here until all packages have been gone through. I’m suffering a concussion right now so I’m sadly of less help than I anticipated

**Comment by clauswilke** [comment]
@paleolimbot The vdiffr failures are due to this PR: https://github.com/tidyverse/ggplot2/pull/2996
which closed this bug: https://github.com/tidyverse/ggplot2/issues/2687

The package authors will have to fix their vdiffr reference images. However, vdiffr is not run on CRAN, so this should not trigger problems there.

However, this should be stated explicitly in the release notes. I'll open an issue to remind us.

**Comment by clauswilke** [comment]
The `geom_ribbon()` problem is related to this conversation:
https://github.com/tidyverse/ggplot2/pull/3235#issuecomment-482605641

Maybe we should revisit this one more time and accept `ymin` and `ymax` as parameters after all. As much as we generally don't want people feeding in data through parameters, the truth is people insist on doing it and overall I think we've given up enforcing this. (See also: https://github.com/tidyverse/ggplot2/pull/2694)

**Comment by clauswilke** [comment]
In reading over the `annotate()` code, I notice that it treats position aesthetics differently from other ones:
``` r
library(ggplot2)
data <- data.frame(x = c(1, 2), y = c(1, 2), facet = c("a", "b"))
p <- ggplot(data, aes(x, y)) + geom_point() + facet_grid(vars(facet))
p + annotate("text", x = c(1, 2), y = 1.5, label = "label")
```



<sup>Created on 2019-05-06 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

Specifically, it only transfers position values into the data frame it creates:
https://github.com/tidyverse/ggplot2/blob/92d27779e210ce16f441eeec26926b8b045a47a8/R/annotation.r#L57

Maybe `annotate()` should poll the geom about the aesthetics it understands and move all those into the newly generated data frame. For reference, this is how `layer()` figures out the aesthetics of a geom: https://github.com/tidyverse/ggplot2/blob/92d27779e210ce16f441eeec26926b8b045a47a8/R/layer.r#L105

**Comment by clauswilke** [comment]
I made a new issue for the annotation problem (#3305).

**Comment by thomasp85** [comment]
Regarding `geom_ribbon()` I looked into that during the last release cycle for what became 3.1.1. bayesAB is torturing the API and I think we should tell them to stop doing that instead of making our code fit their use

**Comment by clauswilke** [comment]
@paleolimbot Could you open a separate issue for each remaining group of problems (for which I haven't opened one yet) and tag each with the 3.2.0 milestone? Then we can triage there. Ignore installation failures, package failures, etc. Only the issues that were brought about by some identifiable change in the ggplot2 code.

**Comment by clauswilke** [comment]
I don't think there's a generic answer to how we address these issues. It depends on how many downstream packages are affected, how difficult it would be for us to restore the previous behavior, and how strongly we believe that the new behavior is more appropriate/correct. Contacting the downstream maintainers and telling them that they need to fix something is always an option, but if it's easy for us to prevent a problem then we should rather do that.

**Comment by hadley** [comment]
Replaced by #3352

**Pull request closed without merging**
