### PR TITLE
README Typo, Capitalization Changes

### PR DESCRIPTION
**Pull request by carywreams**
Found this while looking to contribute for another Documentation item.
Did not find an open issue for any of these items in the README file.

git log entry: 
```
    Typo: "the the" to "the" in installation instructions
    Changes Capitalization of Book and Chapter names:
        Data Visualisation chapter ref (anchor only)
        Graphics for communication (anchor only, matches actual)
        R for Data Science book name (anchor and text usage)
```

### Notes
Looked at a couple of other ```README.Rmd``` PRs.

Did not see changes to ```README.md``` in the PR, so making assumption that's somehow automated and out-of-scope for a README PR.  

If needed here, will need instructions of generating an updated ```README.md``` from the ```.Rmd``` file.

### CODE REVIEW

**Comment by clauswilke** [comment]
To update `README.md`, please open `README.Rmd` in RStudio and click on the "knit" button. Then ament your PR so it contains both the updated `README.Rmd` and the updated  `README.md`. Thanks!

**Comment by carywreams** [comment]
Ah. 
Don't suppose  there's a command line option for this ?
If not, will take me a bit to get RStudio up and running to submit the PR for the README.

**Comment by carywreams** [comment]
ok.

Managed to get that to work via RStudio, but there was a side effect: A png file was re-created (git diff says these files are different).

I suspect this was expected, so I left it in the commit.

**Comment by clauswilke** [comment]
The new png is much smaller than the old one. @yutannihilation Any idea why by any chance? Did the default format change?

**Comment by clauswilke** [comment]
One more request, while you're at it: Could you change the URLs to https where they exist (probably all of them)?

**Comment by yutannihilation** [comment]
Not sure what causes the change (Pandoc 2 become smarter to resize the image to the necessary size?), but it seems reproducible. So, I think it's OK to merge.

Confession: I cheated on https://github.com/tidyverse/ggplot2/pull/3632 by editing `README.md` by hand, sorry... :roll_eyes:

**Comment by carywreams** [comment]
okay - updated those specs to be https.

while testing the links, noticed many were converting to https at the site anyway (they were all updated in the README, regardless).

the png file did not re-gen upon this knitting.

**Pull request merged**
