### PR TITLE
Correct a spelling mistake in the documatation of continuous_scale

### PR DESCRIPTION
**Pull request by microly**
Correct a spelling mistake in this line:

https://github.com/tidyverse/ggplot2/blob/5dfe49829d9b0b35f9cf0783d9915c6112f88eec/R/scale-.r#L52

It should be "scales, which always use [scales::rescale()]. ".

### CODE REVIEW

**Comment by yutannihilation** [comment]
Thanks! Could you regenerate the documents by `devtools::document()`? If you don't know how to do, don't worry, we'll take care of it.

**Comment by microly** [comment]
Thanks for your reply!
I am not familiar with regenerating the documents, but I will try it in my free time.

**Comment by microly** [comment]
Is it ok now?
@yutannihilation

**Comment by microly** [comment]
Thanks for merging!

**Pull request merged**
