### PR TITLE
Free scales for `coord_polar()`

### LINKED ISSUE #2815: Awkward interaction between faceting, polar coordinates, and free scales
The concept of free scales under faceting doesn't quite work the way I would think it should when we're dealing with polar coordinates.

If we make set of facets with simple polar bar plots, we get partial pies because by default the scales are the same across facets:
``` r
library(ggplot2)

ggplot(mpg, aes(x = 1, fill = drv)) + 
  geom_bar() +
  coord_polar(theta = "y") +
  facet_wrap(~manufacturer)
```

Trying to make the scales free, so that each facet has its own theta scale, doesn't work, because `coord_polar()` needs a fixed aspect ratio and hence `coord_polar()$is_free()` returns `FALSE`:
``` r

ggplot(mpg, aes(x = 1, fill = drv)) + 
  geom_bar() +
  coord_polar(theta = "y") +
  facet_wrap(~manufacturer, scales = "free_y")
#> Error: coord_polar doesn't support free scales
```

However, we can make a version of `coord_polar()` that returns `TRUE` and it works just fine and makes the pie charts as expected. But then the aspect ratio is wrong:
``` r
cp <- coord_polar(theta = "y")
cp$is_free <- function() TRUE

ggplot(mpg, aes(x = 1, fill = drv)) + 
  geom_bar() +
  cp +
  facet_wrap(~manufacturer, scales = "free")
```

It seems to me that there are two separate concepts that are being muddled together, the aspect ratio of the facets and the limits of the scales. For most coordinate systems these two concepts are linked one-to-one, but for some (like `coord_polar()`) they are not.

### PR DESCRIPTION
**Pull request by teunbrand**
This PR aims to fix #2815.

Briefly, it implements the suggestion to have `CoordPolar$is_free()` return `TRUE`. 

To deal with the aspect ratio, the requirement for fixed scales to have  `Coord`s affect the aspect ratio is dropped. I have so far failed to come up with examples where this may lead to awkward situations, so I hope I'm avoiding Chesterton's Fence here. This requirement was originally implemented in cd11888, but `coord_equal()`'s behaviour appears unaffected by this PR.

Also, a complication arose in https://github.com/tidyverse/ggplot2/issues/2815#issuecomment-698932620.  With this PR, `coord_equal()` can also have free scales in `facet_grid()`, but these are of course locked to the column for x-axes and to the rows for y-axes (see also #1344 and #1152, which might be a topic revisiting separately from this PR). Because `theta` can be either axis, it has no special relation with either horizontal or vertical directions, which makes this a bit awkward.

### CODE REVIEW

**Comment by thomasp85** [comment]
is this tangentially related enough to the milestone for inclusion?

**Comment by teunbrand** [comment]
Might be nice, but should double check if this holds for `coord_radial()` as well

**Comment by teunbrand** [comment]
Yeah lets include this in the milestone, why not?

**Comment by thomasp85** [comment]
is it ready for review?

**Comment by teunbrand** [comment]
Yes, I'll request it

**Review by thomasp85 — APPROVED** [review]
LGTM

**Comment by teunbrand** [comment]
Thanks!

**Pull request merged**
