### PR TITLE
updated revdeps for 2.2.1 vs 2.2.1.9000

### PR DESCRIPTION
**Pull request by topepo**
## revdepcheck results

We checked 2105 reverse dependencies (1715 from CRAN + 390 from BioConductor), comparing R CMD check results across CRAN and dev versions of this package.

 * We saw 101 new problems
 * We failed to check 63 packages

Issues with CRAN packages are summarised below.

### New problems
(This reports the first line of each new failure)

* bayesAB
  checking tests ...

* bayesplot
  checking examples ... ERROR
  checking tests ...

* benchmark
  checking whether package ‘benchmark’ can be installed ... WARNING

* benchr
  checking tests ...

* billboarder
  checking examples ... ERROR
  checking re-building of vignette outputs ... WARNING

* BioPET
  checking examples ... ERROR

* cellWise
  checking re-building of vignette outputs ... WARNING

* census
  checking re-building of vignette outputs ... WARNING

* choroplethr
  checking examples ... ERROR

* civis
  checking tests ...

* clustree
  checking examples ... ERROR
  checking re-building of vignette outputs ... WARNING

* colorplaner
  checking examples ... ERROR
  checking tests ...
  checking re-building of vignette outputs ... WARNING

* cosinor2
  checking examples ... ERROR

* countytimezones
  checking re-building of vignette outputs ... WARNING

* cowplot
  checking tests ...

* cricketr
  checking whether package ‘cricketr’ can be installed ... WARNING

* dartR
  checking examples ... ERROR

* DendroSync
  checking examples ... ERROR

* dgo
  checking tests ...

* directlabels
  checking examples ... ERROR
  checking tests ...

* dMod
  checking examples ... ERROR
  checking re-building of vignette outputs ... WARNING

* dpcR
  checking re-building of vignette outputs ... WARNING

* drugCombo
  checking tests ...
  checking re-building of vignette outputs ... WARNING

* eeptools
  checking whether package ‘eeptools’ can be installed ... WARNING

* emojifont
  checking re-building of vignette outputs ... WARNING

* expss
  checking re-building of vignette outputs ... WARNING

* extracat
  checking examples ... ERROR

* fastR2
  checking examples ... ERROR
  checking whether package ‘fastR2’ can be installed ... WARNING

* fiftystater
  checking re-building of vignette outputs ... WARNING

* forecast
  checking examples ... ERROR

* ForecastComb
  checking whether package ‘ForecastComb’ can be installed ... WARNING

* foreSIGHT
  checking examples ... ERROR
  checking re-building of vignette outputs ... WARNING

* fpp2
  checking whether package ‘fpp2’ can be installed ... WARNING

* GeomComb
  checking whether package ‘GeomComb’ can be installed ... WARNING

* ggedit
  checking examples ... ERROR

* ggetho
  checking examples ... ERROR
  checking tests ...

* ggFacetSample
  checking examples ... ERROR

* ggfan
  checking re-building of vignette outputs ... WARNING

* ggforce
  checking examples ... ERROR
  checking for code/documentation mismatches ... WARNING
  checking re-building of vignette outputs ... WARNING

* ggformula
  checking examples ... ERROR
  checking re-building of vignette outputs ... WARNING

* ggfortify
  checking tests ...

* gggenes
  checking examples ... ERROR
  checking tests ...
  checking re-building of vignette outputs ... WARNING

* gghighlight
  checking examples ... ERROR
  checking tests ...

* ggiraphExtra
  checking examples ... ERROR
  checking tests ...
  checking re-building of vignette outputs ... WARNING

* ggmap
  checking examples ... ERROR

* ggmosaic
  checking examples ... ERROR
  checking re-building of vignette outputs ... WARNING
  checking Rd \usage sections ... NOTE

* ggpol
  checking examples ... ERROR
  checking re-building of vignette outputs ... WARNING

* ggpubr
  checking examples ... ERROR

* ggpval
  checking examples ... ERROR
  checking tests ...
  checking re-building of vignette outputs ... WARNING

* ggraph
  checking examples ... ERROR
  checking S3 generic/method consistency ... WARNING
  checking re-building of vignette outputs ... WARNING
  checking Rd \usage sections ... NOTE

* ggseas
  checking examples ... ERROR
  checking tests ...
  checking re-building of vignette outputs ... WARNING

* ggstance
  checking tests ...

* ggtern
  checking examples ... ERROR

* ggthemes
  checking examples ... ERROR

* healthcareai
  checking tests ...

* heatmaply
  checking tests ...

* hurricaneexposure
  checking examples ... ERROR

* hyperSpec
  checking examples ... ERROR

* imputeTestbench
  checking whether package ‘imputeTestbench’ can be installed ... WARNING

* incidence
  checking examples ... ERROR
  checking re-building of vignette outputs ... WARNING

* jcolors
  checking examples ... ERROR

* jtools
  checking tests ...
  checking re-building of vignette outputs ... WARNING

* knitrBootstrap
  checking re-building of vignette outputs ... WARNING

* lavaSearch2
  checking whether package ‘lavaSearch2’ can be installed ... WARNING

* lime
  checking tests ...

* mafs
  checking whether package ‘mafs’ can be installed ... WARNING

* model4you
  checking examples ... ERROR

* mosaic
  checking examples ... ERROR

* mosaicModel
  checking re-building of vignette outputs ... WARNING

* munsell
  checking examples ... ERROR

* oddsratio
  checking examples ... ERROR
  checking tests ...
  checking re-building of vignette outputs ... WARNING

* OECD
  checking re-building of vignette outputs ... WARNING

* penaltyLearning
  checking tests ...

* phyloseqGraphTest
  checking examples ... ERROR
  checking re-building of vignette outputs ... WARNING

* platetools
  checking examples ... ERROR

* plotly
  checking tests ...

* plotROC
  checking re-building of vignette outputs ... WARNING

* propr
  checking re-building of vignette outputs ... WARNING

* quanteda
  checking tests ...

* quickpsy
  checking examples ... ERROR

* RBesT
  checking re-building of vignette outputs ... WARNING

* reghelper
  checking tests ...

* robustbase
  checking running R code from vignettes ...

* rotations
  checking installed package size ... NOTE

* RStoolbox
  checking examples ... ERROR

* rusk
  checking examples ... ERROR

* scatterpie
  checking examples ... ERROR
  checking re-building of vignette outputs ... WARNING

* Seurat
  checking tests ...

* sugrrants
  checking examples ... ERROR
  checking re-building of vignette outputs ... WARNING

* surveillance
  checking examples ... ERROR

* sValues
  checking examples ... ERROR

* svdvis
  checking examples ... ERROR
  checking re-building of vignette outputs ... WARNING

* synthpop
  checking examples ... ERROR

* trackr
  checking examples ... ERROR
  checking tests ...

* ukgasapi
  checking examples ... ERROR

* usmap
  checking tests ...

* vdmR
  checking examples ... ERROR

* voxel
  checking examples ... ERROR

* WRTDStidal
  checking whether package ‘WRTDStidal’ can be installed ... WARNING

* xkcd
  checking examples ... ERROR

* xpose
  checking examples ... ERROR
  checking tests ...
  checking re-building of vignette outputs ... WARNING
  checking installed package size ... NOTE

### Failed to check

* aslib                  (failed to install)
* BACA                   (failed to install)
* BACCT                  (failed to install)
* bamdit                 (failed to install)
* BayesRS                (failed to install)
* BNSP                   (failed to install)
* BPEC                   (failed to install)
* broom                  (check timed out)
* bsam                   (failed to install)
* BTSPAS                 (failed to install)
* classify               (failed to install)
* CollapsABEL            (failed to install)
* crmPack                (failed to install)
* Crossover              (failed to install)
* Deducer                (failed to install)
* dendroTools            (failed to install)
* DiversityOccupancy     (failed to install)
* dynr                   (failed to install)
* evoper                 (failed to install)
* ewoc                   (failed to install)
* Fgmutils               (failed to install)
* fingerPro              (failed to install)
* G2Sd                   (failed to install)
* imageData              (failed to install)
* InSilicoVA             (failed to install)
* llama                  (failed to install)
* magick                 (failed to install)
* matchingMarkets        (failed to install)
* mbgraphic              (failed to install)
* microplot              (failed to install)
* mleap                  (failed to install)
* morse                  (failed to install)
* mwaved                 (failed to install)
* OpenStreetMap          (failed to install)
* openVA                 (failed to install)
* pcaPA                  (failed to install)
* petro.One              (failed to install)
* phase1RMD              (failed to install)
* phylosim               (check timed out)
* PortfolioEffectHFT     (failed to install)
* qdap                   (failed to install)
* RcmdrPlugin.FuzzyClust (check timed out)
* ReporteRs              (failed to install)
* RJafroc                (failed to install)
* rmcfs                  (failed to install)
* rpanel                 (failed to install)
* rrepast                (failed to install)
* rsvg                   (failed to install)
* RtutoR                 (failed to install)
* seewave                (failed to install)
* SensMap                (failed to install)
* SeqFeatR               (failed to install)
* sf                     (failed to install)
* sgmcmc                 (check timed out)
* simmr                  (failed to install)
* simulator              (check timed out)
* spcosa                 (failed to install)
* subspaceMOA            (failed to install)
* TeachingDemos          (check timed out)
* thinkr                 (failed to install)
* vortexR                (failed to install)
* XLConnect              (failed to install)
* zooaRchGUI             (failed to install)

### CODE REVIEW

**Comment by hadley** [comment]
I suspect we missed something major or introduced a new regression 🙁

**Comment by karawoo** [comment]
😭 @hadley let me know if it would be helpful work on this some in person in the next couple days

**Comment by hadley** [comment]
@karawoo yeah, that would be great!

**Comment by batpigandme** [comment]
Stuck on airplane with slow wifi anyhow, if you want basic
clustering/triage LMK.

**Comment by hadley** [comment]
We did reduce it by ~120 problems; so not actually that bad, just not as good as I'd hoped :/

**Comment by hadley** [comment]
Google docs seems to be down for me right now, but I'll make another triage list once it's up.

**Comment by batpigandme** [comment]
10-4.
FTR, I'm in the ggplot2 revdeps sheet now, so it appears to be on the up
and up.

**Comment by hadley** [comment]
Still down for me 😢. But I've done a scan through problems.md; I don't think we've missed anything big - there are just a bunch of failures related to tidy eval, slightly modifications to the extensions API, and the stricter data frame creation.  We need to create a minimal reprex "`data` must be uniquely named but has duplicate elements" and fix the `if (position != "none")` bug, but otherwise I think we can send out emails on Monday.

**Pull request merged**
