### PR TITLE
WIP: Add scale_color_viridis_b

### PR DESCRIPTION
**Pull request by xvrdm**
Add missing British to American spellings for scale_colour_viridis_b()

### CODE REVIEW

**Comment by xvrdm** [comment]
Need to generate documentation once I have a real internet connexion.

**Comment by yutannihilation** [comment]
@xvrdm Thanks for catching this. Can you regenerate the docs? (You need the latest version of roxygen2)

**Comment by yutannihilation** [comment]
Hmm, I tried to generate the doc (for the alias), but it seems you don't permit me to edit your branch...

**Comment by yutannihilation** [comment]
I'll take care of it in another pull request. Thanks for your contribution!

**Comment by xvrdm** [comment]
Hey @yutannihilation ,
Very sorry for the lack of answer, change of country and job for me this month :/ 
Thanks a lot for finishing and merging this !

**Comment by yutannihilation** [comment]
No worries, thanks for contributing during such a busy time!

**Pull request merged**
