### PR TITLE
fix alignment problem

### LINKED ISSUE #4350: alignment problem with preserve = "single" and preserve = "total"
This issue is a follow-up on https://github.com/tidyverse/ggplot2/issues/2712#issue-335176790.

The previously posted solution does not work when there are 3 grouping levels, in which case the geom_point and geom_boxplot layers no longer match up again.

Reprex:
```r
mtcars2 <- bind_rows(mtcars, data.frame(gear = c(4,5), mpg = c(22, 19), am = c(2, 2)))
ggplot(mtcars2, aes(factor(gear), mpg, fill = factor(am))) + 
   geom_boxplot(position = position_dodge2(0.75, preserve = 'single')) +
   geom_point(position = position_dodge(0.75, preserve = 'total'))
```

### PR DESCRIPTION
**Pull request by javlon**
Fix #4350 

This PR fixes the alignment problem. The problem is fixed by creating normalized fake width.

### CODE REVIEW

**Comment by thomasp85** [comment]
@karawoo would you be able to take a look at this?

also, @javlon have you fixed the issue pointed out by @smouksassi in #4350?

**Comment by javlon** [comment]
> @karawoo would you be able to take a look at this?
> 
> also, @javlon have you fixed the issue pointed out by @smouksassi in #4350?

Sorry I haven't seen this issue. The only way to fix mentioned issue requires changes in the `position_dodge` algorithm. Changes include information about the `width` of the boxplot (or any other object) from `position_dodge2`. It means `position_dodge` should know information about other layers which might lead to more trouble in the future than the proposed solution. 

Above PR include changes only in the `position_dodge2` algorithm, and now it has the same algorithm for position selection as `position_doge`.

Yes, the distance between boxplots has changed slightly, but the overall width for each group is constant.

**Comment by karawoo** [comment]
I should say @javlon that I really appreciate you working on this and your solution does look really good for basic boxes + points. It's just a tricky problem with a lot of edge cases, unfortunately 😕

**Comment by javlon** [comment]
Thank you, @karawoo, for your clear explanation of the problem. I forgot about this kind of usage of boxplots.

**Pull request closed without merging**
