### PR TITLE
specific behavior of geom_dotplot()

### PR DESCRIPTION
**Pull request by gael-millot**
news examples that include the specific behavior of geom_dotplot()

### CODE REVIEW

**Comment by thomasp85** [comment]
This amount of examples seems a bit excessive as we need to be mindful about keeping check time low - could you trim it down to two?

**Comment by clauswilke** [comment]
Also, a few additional comments:

- Please format code according to the [tidyverse style guide](https://style.tidyverse.org/)
- Please remove the `ggplot2::` prefixes; they make the examples difficult to read
- If you're relabeling the factors, why use generic labels A and B instead of labels that are meaningful for the data you're plotting? (e.g., `vs` indicates whether an engine is V-shaped or straight)

**Comment by thomasp85** [comment]
Closing this as it seems inactive

**Comment by gael-millot** [comment]
> 
> 
> Closing this as it seems inactive

Hi. Sorry. It is not inactive. It is on my todo list. I'd like to contribute but I am overwhelmed by the pandemia right now. If it is possible to keep it inactive for more time, could you reopen it ? Many thanks.

**Comment by thomasp85** [comment]
Sure — I'll remove it from the milestone

**Comment by hadley** [comment]
Let's close this for now since we're actively triaging issues and PRs.  @gael-millot you're very welcome to re-open once you get back to it.

**Pull request closed without merging**
