### PR TITLE
purrr style lambda notation in scale arguments

### PR DESCRIPTION
**Pull request by teunbrand**
This PR aims to enable purrr style lambda notation for scale arguments that accept functions (`limits`, `breaks`, `minor_breaks`, `labels`, `rescaler` and `oob`). It does so by converting formulas to functions in the scale constructors. Thomas mentioned that lambda notation should work in https://github.com/tidyverse/ggplot2/issues/4173#issuecomment-683742992, but the notation is currently not enabled. 

This PR has partial overlap in scope and in functions altered with #4188. Notable differences are that this PR doesn't touch facet labellers, but applies the lambda notation to more arguments and in all three types of scales (continuous, binned and discrete).

Thank you for considering!

### CODE REVIEW

**Comment by teunbrand** [comment]
I came across issue #4103 as well, which seemed related and worth mentioning.

**Review by yutannihilation — APPROVED** [review]
Looks great!

@thomasp85 
Can we have this in 3.3.4?

**Comment by yutannihilation** [comment]
@thomasp85
I'm merging this if there's no concern. This supersedes some part of #4188, and as #4188 is in the milestones for v3.3.4, I think it's good to include this in v3.3.4.

**Comment by thomasp85** [comment]
Sorry for lack of response, go ahead and merge

**Comment by yutannihilation** [comment]
It's fine. Thanks for confirming!

**Pull request merged**
