### PR TITLE
Expose position arg on geom_hline() and geom_vline()

### LINKED ISSUE #4285: Feature request:  Add position argument to geom_vline and geom_hline
When working with a discrete scale, I'd like to be able to nudge a vline a bit.  But, `geom_vline()` doesn't use the position argument that I would have expected.  It would be helpful to add a `position` argument to `geom_vline()` and `geom_hline()` to allow nudging the position.

In this example, I'd like to have the red vertical line go between the `"1"` and `"2"` on the horizontal axis.

``` r
library(ggplot2)
mydata <-
  data.frame(
    x=factor(c("1", "2")),
    y=3:4
  )
ggplot(mydata, aes(x=x, y=y)) +
  geom_point() +
  geom_vline(xintercept="2", colour="red")
```

``` r
ggplot(mydata, aes(x=x, y=y)) +
  geom_point() +
  geom_vline(xintercept="2", colour="red", position=position_nudge(x=-0.5))
#> Warning: Ignoring unknown parameters: position
```

<sup>Created on 2020-12-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

### PR DESCRIPTION
**Pull request by yutannihilation**
Fix #4285

### CODE REVIEW

**Comment by thomasp85** [comment]
Have you tested how this behaves with other positions than `position_nudge()`? I'm fine with it not working but I could envision some hard-to-understand errors

**Review by thomasp85 — APPROVED** [review]

**Comment by yutannihilation** [comment]
Hmm, no. And, sorry, I think I tested this quickly with the similar code to https://github.com/tidyverse/ggplot2/issues/4285#issuecomment-739753955 and thought it works, but it was probably just I forgot to change `as.numeric(x)`. This seems some more tweaks. I don't see immediately the reason why this doesn't work.

``` r
library(ggplot2)

mydata <- data.frame(
  x = factor(c("1", "2", "3")),
  y = c(3, 4, 5)
)
mydata$splits <- factor(mydata$x, labels = c("baseline", "Cycle 1", "Cycle 1"))

devtools::load_all("~/repo/ggplot2/")
#> ℹ Loading ggplot2

pos <- position_nudge(x = -0.1)

# works
ggplot(mydata, aes(x, y)) +
  geom_point(size = 3, position = pos) +
  geom_vline(
    aes(xintercept = as.numeric(x)),
    alpha = 0.2, size = 5,
    colour = "red",
    position = pos
  )
```



``` r
# doesn't work
ggplot(mydata, aes(x, y)) +
  geom_point(size = 3, position = pos) +
  geom_vline(
    aes(xintercept = x),
    alpha = 0.2, size = 5,
    colour = "red",
    position = pos
  )
#> Warning in Ops.factor(x, params$x): '+' not meaningful for factors
#> Warning: Removed 3 rows containing missing values (geom_vline).
```



<sup>Created on 2021-03-25 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by thomasp85** [comment]
@yutannihilation do you think it is feasible to have this PR done this week? I'm beginning to wrap up the patch release

**Comment by yutannihilation** [comment]
Sorry, I'm afraid I can't... I thought this was as easy job as just exposing the argument, but it turned this requires a better understanding about how position works, which I don't know yet.

**Comment by thomasp85** [comment]
No problem - I've moved all other position related issues to next release because it seems to be a huge work getting it all fixed coherently

**Comment by yutannihilation** [comment]
I see, thanks for handling the release!

**Comment by hadley** [comment]
@yutannihilation do you still think this is worth finishing off?

**Comment by yutannihilation** [comment]
Yes, but I don't think I can finish this soon. I'm giving up for now, sorry.

**Comment by teunbrand** [comment]
The issue in https://github.com/tidyverse/ggplot2/pull/4286#issuecomment-806911135 is that `xintercept` in not a member of `scale_x_discrete()$aesthetics`. That problem should get fixed by #5640, and this PR improves the lack of position adjustments.

@yutannihilation Is there any chance I could convince you to revive this PR? If you don't have a luxurious amount of free time on your hands I wouldn't mind recreating it anew.

**Comment by teunbrand** [comment]
> I just quit my job today

I hope this was by choice and works out in your favour!

There isn't any hurry in this, but I think this PR is the right solution for the problem.

**Comment by yutannihilation** [comment]
Thanks. It's my choice, so don't worry about me.

I hope I'll start addressing on this next week!

**Pull request closed without merging**
