### PR TITLE
Don't strip classes in `Geom$use_defaults()`

### LINKED ISSUE #5656: Support for using `I()`  to use NPC corodinates seems incomplete
@teunbrand I could not find an open issue on this, but I remember seeing a rather recent commit by you implementing this new feature. In 3.4.4.9000 I see it working in `annotate()` and in `aes()` but not with values mapped to constants in calls to geoms (at least `geom_label()`). By the way, it is great to see this implemented in 'ggplot2'. It makes several geometries in 'ggpp' redundant which is, I think, an indication of usefulness, as now all geometries become usable with NPC coordinates.

``` r
library(ggplot2)

ggplot(data = mtcars,
       mapping = aes(x = disp, y = mpg, colour = factor(cyl))) +
  geom_point() +
  annotate(geom = "label", x = I(0.5), y = I(0.9), label = "a label")
```

``` r

ggplot() +
  geom_point(mapping = aes(x = disp, y = mpg, colour = factor(cyl)),
             data = mtcars) +
  geom_label(mapping = aes(x = I(x), y = I(y), label = label),
             data = data.frame(x = 0.5, y = 0.9, label = "a label"))
```

``` r

ggplot(data = mtcars,
       mapping = aes(x = disp, y = mpg, colour = factor(cyl))) +
  geom_point() +
  geom_label(x = I(0.5), y = I(0.9), label = "a label", colour = "black")
```

``` r

ggplot(data = mtcars,
       mapping = aes(x = disp, y = mpg, colour = factor(cyl))) +
  geom_point() +
  geom_label(x = 300, y = 32, label = "a label", colour = "black")
```

<sup>Created on 2024-01-22 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

### PR DESCRIPTION
**Pull request by teunbrand**
This PR to the RC aims to fix #5656.

Briefly, using ``base::`<-.data.frame` `` in `Geom$use_defaults()` causes classes to be stripped on the RHS of the assignment.
This PR uses `vec_cbind()` to do the same job without stripping classes.
I encountered some reordered rownames during a test, but as these are not important in ggplot2, I'm not concerned.

### CODE REVIEW

**Comment by thomasp85** [comment]
how come row names order is affected at all? The code change doesn't do any reordering?

**Comment by teunbrand** [comment]
I think in some circumstances `vec_cbind()` just resets rownames to their defaults.

``` r
df <- data.frame(x = 1:2, y = 1:2)
rownames(df) <- 3:2
rownames(df)
#> [1] "3" "2"
rownames(vctrs::vec_cbind(df, !!!list(i = 3)))
#> [1] "1" "2"
```

<sup>Created on 2024-01-22 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by thomasp85** [comment]
gotcha

**Review by thomasp85 — APPROVED** [review]
LGTM

**Pull request merged**
