### PR TITLE
Add "Get started" section on the pkgdown site

### PR DESCRIPTION
**Pull request by yutannihilation**
A followup of #5159

cf. https://pkgdown.r-lib.org/reference/build_site.html#navigation-bar

### CODE REVIEW

**Review by teunbrand — APPROVED** [review]
Awesome, thanks for catching this! I wanted to include this in #5159 but couldn't figure it out right away.

**Comment by yutannihilation** [comment]
Thanks, I too didn't know this convention until today :)

**Comment by yutannihilation** [comment]
Hmm, I still cannot see the "Get started" in the navvar of https://ggplot2.tidyverse.org/dev/index.html. Sorry, it seems I misunderstand the rule...

image

**Comment by yutannihilation** [comment]
Now I see it. It seems the deployment didn't succeed at this commit.

https://github.com/tidyverse/ggplot2/actions/runs/6158393380/job/16711101201

**Comment by teunbrand** [comment]
The 'Get started' now shows up, so I guess this has magically resolved itself :)

**Pull request merged**
