### PR TITLE
Stats imports

### LINKED ISSUE #5186: Several occurrences of unimported `stats` and `utils` function calls
There appear to be several occurrences of `stats` and `utils` function calls that are not imported and not declared explicitly (as e.g. `stats::approx()` or `utils::getFromNamespace()`):

```{r}
* Source code references:
  approx at axis-secondary.R#239:
    239: old_val <- approx(full_range, old_range, range_info$major_source)$y
  approx at axis-secondary.R#255:
    255: old_val_minor <- approx(full_range, old_range, range_info$minor_source)$y
  approxfun at stat-align.R#72:
    72: y_val <- approxfun(data$x, data$y)(unique_loc)
  ecdf at stat-ecdf.r#102:
    102: data_ecdf <- ecdf(data$x)(x)
  getFromNamespace at backports.R#4:
    4: absolute.units <- getFromNamespace("absolute.units", "grid")
  getFromNamespace at backports.R#5:
    5: absolute.units.unit <- getFromNamespace("absolute.units.unit", "grid")
  getFromNamespace at backports.R#6:
    6: absolute.units.unit.list <- getFromNamespace("absolute.units.unit.list", "grid")
  getFromNamespace at backports.R#7:
    7: absolute.units.unit.arithmetic <- getFromNamespace("absolute.units.unit.arithmetic", "grid")
  quantile at stat-qq-line.R#79:
    79: y_coords <- quantile(sample, line.p)
```

### PR DESCRIPTION
**Pull request by klin333**
Add utils:: and stats:: in front of functions not explicitly imported.

Fixes #5186

### CODE REVIEW

**Review by teunbrand — APPROVED** [review]
Thanks for the PR, the proposed changed look good to me.
Can I just quickly check in that these changes have resolved the issue that you were experiencing?

**Comment by klin333** [comment]
yes, this use to complain about approxfun not found: ```tibble(x = seq(10), y = seq(10)) %>% ggplot() + geom_area(aes(x = x, y = y))```. But it works now.

**Comment by klin333** [comment]
also note that utils::head and utils::tail are used in various places in ggplot2. i didn't prepend utils:: to them as i didn't want to make too many file changes. probably best to explicitly import these 2 functions in ggplot2-package.R?

**Comment by teunbrand** [comment]
> probably best to explicitly import these 2 functions in ggplot2-package.R?

Yeah that might be wise. You could use `usethis::use_import_from("utils", c("head", "tail"))` to automatically write the namespace as well.

**Comment by teunbrand** [comment]
Great, thanks for the contribution!

**Pull request merged**
