### PR TITLE
[CI] Switch to pak

### LINKED ISSUE #4424: pkgdown CI error
https://github.com/tidyverse/ggplot2/runs/2360094189#step:9:464
```
-- RMarkdown error -------------------------------------------------------------
Quitting from lines 372-382 (faq-axes.Rmd) 
Error: Error in loadNamespace(name) : there is no package called 'ggtext'
--------------------------------------------------------------------------------
Error: Error: Failed to render RMarkdown
```

### PR DESCRIPTION
**Pull request by yutannihilation**
Fix #4424

Test build: https://github.com/yutannihilation/ggplot2/runs/2361972393

### CODE REVIEW

**Comment by thomasp85** [comment]
Thanks - there's a new GHA that uses pak and does all of this automatically, so we'll be migrating to that instead

**Comment by yutannihilation** [comment]
Hmm, yeah, using pak seems better. This pull request still fails to build the pkgdown site...

```
ERROR: dependencies ‘gtable’, ‘isoband’, ‘scales’ are not available for package ‘ggplot2’
```

**Comment by yutannihilation** [comment]
Switched to pak and this seems to work.

https://github.com/yutannihilation/ggplot2/runs/2362084213

**Comment by thomasp85** [comment]
Since you are as far as I am and have a better feeling for the CI scripts do you mind updating all the scripts to use pak, i.e. run `usethis::use_tidy_github_actions()` with the dev version of usethis and make sure to not remove stuff we have added?

**Comment by yutannihilation** [comment]
Oh, sure. I will.

**Comment by yutannihilation** [comment]
It seems `pak::pkg_deps()` doesn't work when there's unavailable packages. We need to fix pak first...

**Comment by yutannihilation** [comment]
It turned out pak is not ready to use in our repo. I'll think if we can add some (probably not very simple) workaround or give up for now.

**Comment by thomasp85** [comment]
Ok, let's just fix the pkgdown build for now then... will you roll back the last commits?

**Comment by yutannihilation** [comment]
Reverted. I'll file a new issue for migrating `R-CMD-check.yaml` to pak when it's ready.

**Review by thomasp85 — APPROVED** [review]

**Pull request merged**
