### PR TITLE
Pass fill value to legend key icons

### PR DESCRIPTION
**Pull request by 808sAndBR**
Resolves: #3455 

Below is reprex of this working:

```
# sample data
dat <- data.frame(
  x = as.factor(1:10),
  y = c(20,30,13,37,12,50,31,2,40,30),
  z = rep('a', 10)
)

# basic plot
ggplot(dat) +
  geom_segment(
    aes(x = x, xend = x, y = 0, yend = y+15, linetype = z), 
    arrow = arrow(length = unit(0.25, 'cm'), type = 'closed'),
    size = 0.7
  ) 
```

New output:
image

Old output:
image

### CODE REVIEW

**Comment by clauswilke** [comment]
I have two concerns about this:

1. `geom_segment()` has a parameter `arrow.fill`. We should see if we can carry it through to the legend and use if defined.

2. I'm wondering whether this draw key is used by any geoms that meaningfully use a `fill` aesthetic, and whether in this case filling the arrow in the way it is done now will create strange results. Possibly we need a new draw key specifically for `geom_segment()`.

**Comment by thomasp85** [comment]
I don't think we can do this for geom_segment specifically. Any segment and path type geom can have arrowheads and they should behave as expected.

Your concern about the arrow.fill argument is valid though... is there a straightforward way to pass this through?

**Comment by 808sAndBR** [comment]
I believe that this new version passes the arrow.fill through as expected, but let me know if it looks questionable.

For the second concern. I ran this version of legend_draw on everywhere that I saw importing it:

```
geom_sf
geom_errorbar
geom_path
geom_segment
geom_rug
geom_hline
```
None of the outputs seems strange to me, but I have them in a Rmd if you want to swing by and see if you notice anything strange.

**Comment by clauswilke** [comment]
Yes, ignore my 2nd concern, it doesn't apply.

However, for my 1st concern, a little more needs to be done. First, `arrow.fill` should be the first choice for `fill`, not the second, as it is the case in the geom. See here:
https://github.com/tidyverse/ggplot2/blob/7e6d1259237d9a2b48b8156e62ada2c47c411f31/R/geom-segment.r#L116
and here:
https://github.com/tidyverse/ggplot2/blob/7e6d1259237d9a2b48b8156e62ada2c47c411f31/R/geom-segment.r#L121

Second, I doubt `data$arrow.fill` will work. I think it has to be `params$arrow.fill`. In either case, I think it's important that you run a test to check whether this actually works.

Finally, I wouldn't discount the fill variable, so the final sequence should read:
`params$arrow.fill %||% data$colour %||% data$fill %||% "black"`

**Comment by 808sAndBR** [comment]
Thanks for all the extra info, it's been super helpful for understanding how this all works behind the scenes.

Ahhhh, I see I think it picking up "black" from the back of the options which made me think it was working as expected. 

I have added some more robust test cases (below) to  make sure this is working as expected. I think it looks right to me, but let me know if anything seems off.

```{r}
# sample data
dat <- data.frame(
  x = as.factor(1:10),
  y = c(20,30,13,37,12,50,31,2,40,30),
  z = rep('a', 10)
)

# basic plot
ggplot(dat) +
  geom_segment(
    aes(x = x, xend = x, y = 0, yend = y+15, linetype = z), 
    arrow = arrow(length = unit(0.25, 'cm'), type = 'closed'),
    size = 0.7
  ) 
```

image

```{r}
ggplot(dat) +
  geom_segment(
    aes(x = x, xend = x, y = 0, yend = y+15, linetype = z), 
    arrow = arrow(length = unit(0.25, 'cm'), type = 'closed'),
    arrow.fill = 'red',
    size = 0.7
  ) 
```
image

```{r}
ggplot(dat) +
  geom_segment(
    aes(x = x, xend = x, y = 0, yend = y+15, linetype = z, colour='yellow'), 
    arrow = arrow(length = unit(0.25, 'cm'), type = 'closed'),
    size = 0.7
  ) 
```

image

```{r}
ggplot(dat) +
  geom_segment(
    aes(x = x, xend = x, y = 0, yend = y+15, linetype = z, colour='yellow'), 
    arrow = arrow(length = unit(0.25, 'cm'), type = 'closed'),
    arrow.fill = 'blue',
    size = 0.7
  ) 
```

image

**Comment by clauswilke** [comment]
Looks great, thanks! 

Going forward, I suggest you check out the [reprex package,](https://reprex.tidyverse.org/articles/articles/magic-reprex.html) so you don't have to copy and paste screenshots.

**Pull request merged**
