### PR TITLE
Use rlang to generate quosure list

### PR DESCRIPTION
**Pull request by lionel-**
Avoids making assumptions about internals of quosure lists. Fixes a test failure with dev rlang.

### CODE REVIEW

**Comment by hadley** [comment]
Does this just fix broken unit tests, or does it affect the user experience?

**Comment by lionel-** [comment]
This just fixes a broken test that made assumptions about the internals of quosure lists. They now explictly inherit from "list".

**Comment by yutannihilation** [comment]
Maybe this should be included in version 3.3?

**Comment by thomasp85** [comment]
Yes this should be merged into rc as well

**Comment by lionel-** [comment]
Can one of you do it please? I'm not familiar with the rc branch.

**Comment by yutannihilation** [comment]
Sure.

**Pull request merged**
