### PR TITLE
Import lifecycle

### PR DESCRIPTION
**Pull request by romainfrancois**
This seems to address #3900 

I don't really understand why though 🤷‍♂

### CODE REVIEW

**Comment by thomasp85** [comment]
I really don't like doing this without understanding the root cause... we have been working a lot on cutting dependencies so this runs a bit counter to it...

**Comment by clauswilke** [comment]
At some point we re-exported some dplyr functions for some reason. I don't remember the details, but it was necessary at the time. Do we still do that? If yes I bet that's the root cause.

**Comment by clauswilke** [comment]
https://github.com/tidyverse/ggplot2/blob/3ddfc3f30cd072309dcfed020493330af46d4ed6/R/zzz.r#L54-L59

**Comment by romainfrancois** [comment]
Updated based on conversation in #3900

**Pull request merged**
