### PR TITLE
export binned_scale

### PR DESCRIPTION
**Pull request by coolbutuseless**
'discrete_scale' and 'continuous_scale' are both exported.  Can we export 'binned_scale' as well?

### CODE REVIEW

**Comment by clauswilke** [comment]
Closes #3913.

**Comment by clauswilke** [comment]
@coolbutuseless Could you merge in the current master please? Your PR picked up a lot of documentation updates that have been merged already.

**Comment by thomasp85** [comment]
I'm pretty sure this is a result of my call to the GHA document function... still would be nice to get master merged in

**Pull request merged**
