### PR TITLE
Stop using Travis CI and AppVeyor

### PR DESCRIPTION
**Pull request by yutannihilation**
It has been 3 months since we enabled GitHub Actions CI (#3862). While we still need to take care GitHub Actions CI time to time, it seems to catch the unintended changes reliably just as Travis CI and AppVeyor have been doing for years. So, I think it's okay to stop using Travis CI and AppVeyor now.

### CODE REVIEW

**Comment by yutannihilation** [comment]
> We could also remove .travis.yml and appveyor.yml from .Rbuildignore

Thanks! I forgot to do this.

@thomasp85 @clauswilke 
Do you have any concern to stop using Travis CI and AppVeyor? If not, I'll merge this (though it seems we need to change some setting on AppVayor to actually deactivate it)

**Comment by clauswilke** [comment]
I have no strong opinion one way or another.

**Comment by yutannihilation** [comment]
Thanks, Claus. I'm merging this.

**Comment by yutannihilation** [comment]
@thomasp85 @hadley 
Could you disable the integrations with Travis CI and AppVeyor? We now rely only on GitHub Actions CI.

**Pull request merged**
