### PR TITLE
Test: Fix Rd cross-ref warnings on R-devel

### PR DESCRIPTION
**Pull request by yutannihilation**
(This PR is only for testing if the new document generation can pass the checks on r-devel)

* `devtools::install_github("r-lib/roxygen2")`
* ~~Re-generate the document of scales package and installed it~~ (This has been addressed on roxygen2's side)
* Update the documents of `utilities-tidy-eval.R` to [the latest one](https://github.com/r-lib/usethis/blob/master/inst/templates/tidy-eval.R) (Note that I copied only the paragraphs about the functions that are currently re-exported. Let's update it again after the release of v3.3.2. c.f.  #4063)
* Re-generate document of ggplot2

### CODE REVIEW

**Comment by yutannihilation** [comment]
This indicates we might need to re-generate documents not only on ggplot2 it self but also on the packages included by `@inheritParams`... Fortunately, for ggplot2 we only need to handle scales package.

https://github.com/r-lib/roxygen2/pull/1109#issuecomment-643712847

**Comment by thomasp85** [comment]
I'm getting a bunch of warnings locally related to missing docs in scales cross-refs... Is it something in my local setup or can I expect the same on the CRAN check?

**Comment by yutannihilation** [comment]
Hmm, I don't see any warnings on my local Linux with `devtools::check(remote = TRUE, manual = TRUE)`.

Do you mean you ran `devtools::check(remote = TRUE, manual = TRUE)` on your local with R-devel? Or R 4.0.1? It seems you need to do `remotes::install_github("r-lib/roxygen2#1109")` as  `devtools::check()` re-generates documents before starting actual ckeck, iiuc.

**Comment by thomasp85** [comment]
I have the roxygen2#1109 patch and when I document it updates all scale related links... Do you have the cran version of scales on your machine?

**Comment by yutannihilation** [comment]
That's strange... Yes, I have CRAN version of scales installed.

``` r
sessioninfo::package_info(c("scales", "roxygen2"))
#>  package      * version    date       lib source                         
#>  assertthat     0.2.1      2019-03-21 [1] CRAN (R 4.0.0)                 
#>  backports      1.1.7      2020-05-13 [1] CRAN (R 4.0.0)                 
#>  brew           1.0-6      2011-04-13 [1] CRAN (R 4.0.0)                 
#>  callr          3.4.3      2020-03-28 [1] CRAN (R 4.0.0)                 
#>  cli            2.0.2      2020-02-28 [1] CRAN (R 4.0.0)                 
#>  colorspace     1.4-1      2019-03-18 [1] CRAN (R 4.0.0)                 
#>  commonmark     1.7        2018-12-01 [1] CRAN (R 4.0.0)                 
#>  crayon         1.3.4      2017-09-16 [1] CRAN (R 4.0.0)                 
#>  desc           1.2.0      2018-05-01 [1] CRAN (R 4.0.0)                 
#>  digest         0.6.25     2020-02-23 [1] CRAN (R 4.0.0)                 
#>  evaluate       0.14       2019-05-28 [1] CRAN (R 4.0.0)                 
#>  fansi          0.4.1      2020-01-08 [1] CRAN (R 4.0.0)                 
#>  farver         2.0.3      2020-01-16 [1] CRAN (R 4.0.0)                 
#>  glue           1.4.1      2020-05-13 [1] CRAN (R 4.0.0)                 
#>  highr          0.8        2019-03-20 [1] CRAN (R 4.0.0)                 
#>  knitr          1.28       2020-02-06 [1] CRAN (R 4.0.0)                 
#>  labeling       0.3        2014-08-23 [1] CRAN (R 4.0.0)                 
#>  lifecycle      0.2.0      2020-03-06 [1] CRAN (R 4.0.0)                 
#>  magrittr       1.5        2014-11-22 [1] CRAN (R 4.0.0)                 
#>  markdown       1.1        2019-08-07 [1] CRAN (R 4.0.0)                 
#>  mime           0.9        2020-02-04 [1] CRAN (R 4.0.0)                 
#>  munsell        0.5.0      2018-06-12 [1] CRAN (R 4.0.0)                 
#>  pkgbuild       1.0.8      2020-05-07 [1] CRAN (R 4.0.0)                 
#>  pkgload        1.1.0      2020-05-29 [1] CRAN (R 4.0.0)                 
#>  prettyunits    1.1.1      2020-01-24 [1] CRAN (R 4.0.0)                 
#>  processx       3.4.2      2020-02-09 [1] CRAN (R 4.0.0)                 
#>  ps             1.3.3      2020-05-08 [1] CRAN (R 4.0.0)                 
#>  purrr          0.3.4      2020-04-17 [1] CRAN (R 4.0.0)                 
#>  R6             2.4.1      2019-11-12 [1] CRAN (R 4.0.0)                 
#>  RColorBrewer   1.1-2      2014-12-07 [1] CRAN (R 4.0.0)                 
#>  Rcpp           1.0.4.6    2020-04-09 [1] CRAN (R 4.0.0)                 
#>  rlang          0.4.6      2020-05-02 [1] CRAN (R 4.0.0)                 
#>  roxygen2       7.1.0.9000 2020-06-14 [1] Github (r-lib/roxygen2@be0fd82)
#>  rprojroot      1.3-2      2018-01-03 [1] CRAN (R 4.0.0)                 
#>  rstudioapi     0.11       2020-02-07 [1] CRAN (R 4.0.0)                 
#>  scales         1.1.1      2020-05-11 [1] CRAN (R 4.0.1)                 
#>  stringi        1.4.6      2020-02-17 [1] CRAN (R 4.0.0)                 
#>  stringr        1.4.0      2019-02-10 [1] CRAN (R 4.0.0)                 
#>  viridisLite    0.3.0      2018-02-01 [1] CRAN (R 4.0.0)                 
#>  withr          2.2.0      2020-04-20 [1] CRAN (R 4.0.0)                 
#>  xfun           0.14       2020-05-20 [1] CRAN (R 4.0.0)                 
#>  xml2           1.3.2      2020-04-23 [1] CRAN (R 4.0.0)                 
#>  yaml           2.2.1      2020-02-01 [1] CRAN (R 4.0.0)                 
#> 
#> [1] /home/yutani/R/x86_64-pc-linux-gnu-library/4.0
#> [2] /usr/lib/R/library
```

<sup>Created on 2020-06-15 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by thomasp85** [comment]
embarrassing - apparently my environment was messed up and I was on an older scales version 😬 - sorry for the noise

testing now and submitting soon (hopefully)

**Comment by yutannihilation** [comment]
Oh, I see. Thanks for handling the release!

**Pull request merged**
