### PR TITLE
Use vdiffr for visual unit tests

### PR DESCRIPTION
**Pull request by lionel-**

### CODE REVIEW

**Comment by hadley** [comment]
Once you get back from holiday, we should make it a priority to get this merged.

**Comment by lionel-** [comment]
@hadley Now ready to merge. We'll need to update svglite on CRAN before the next ggplot2 release.

**Comment by hadley** [comment]
Let me update the docs to avoid the spurious diffs.

**Comment by hadley** [comment]
Thanks!!

**Pull request merged**
