### PR TITLE
Improve docs for geom_contour as discussed in issue #4324

### PR DESCRIPTION
**Pull request by dmurdoch**

### CODE REVIEW

**Comment by dmurdoch** [comment]
The failures I'm seeing in the tests don't seem to be related to the changes I made.  I did add an example to `?geom_contour`; would that require some change to reference figures?

**Comment by yutannihilation** [comment]
Yes, we can ignore those failures; they are due to a slight change introduced in the recent version of sf (c.f. #4311). Sorry for the confusion.

**Review by yutannihilation — APPROVED** [review]
Looks good!

@clauswilke 
I think this is fine to merge. This is only a Suggest dependency and is just for documentation so we can remove this easily if we found any problem in future. Any concerns?

**Comment by clauswilke** [comment]
No concerns about the external dependency. I haven't carefully checked the various CI failures.

**Comment by yutannihilation** [comment]
Thanks, for R-CMD-check, failures of windows-latest and ubuntu-16.04 is due to visual cases, which #4311 should fix. macOS-latest errors on setting up XQuartz, I guess this is a temporary one. For test-coverage, it fails at the same XQuartz setup. None seems caused by this pull request.

**Comment by yutannihilation** [comment]
Thanks for contributing!

**Pull request merged**
