### PR TITLE
Show proper error when both x and y are specified on stat_density() and stat_ecdf()

### LINKED ISSUE #4776: Confusing error message and documentation for `geom_density`
The documentation and - in the greatest part - error message for `geom_density` is confusing and should be corrected.

Documentation states that the 
```
geom_density() understands the following aesthetics (required aesthetics are in bold):
- x
- y
```
When providing eiter `x` or `y` easthetic, everything works as expected. If trying to map BOTH `x` and `y`, following occurs:

```r
ggplot(diamonds, aes(x = x, y = y)) +
   geom_density()
   
Error in `check_required_aesthetics()`:
! geom_density requires the following missing aesthetics: y
```
Whereas the `y` aesthetic is clearly provided. IMO it should lead the user to the `geom_density2d`.

### PR DESCRIPTION
**Pull request by yutannihilation**
Fix #4776

### CODE REVIEW

**Review by thomasp85 — CHANGES_REQUESTED** [review]
We are now doing unit tests for all errors so can I get you to add tests for this

**Comment by yutannihilation** [comment]
Sure

**Comment by yutannihilation** [comment]
It seems this existing code will be broken by this change. I'm still thinking, but this might mean the same case can be found with `stat_bin()` and `stat_count()`...?

``` r
library(ggplot2)

do_plot <- function() {
  ggplot(mtcars, aes(mpg, factor(cyl))) +
    stat_density(aes(fill = after_stat(density)), geom = "raster", position = "identity")
}

do_plot()
```



``` r

devtools::load_all("~/GitHub/ggplot2/")
#> ℹ Loading ggplot2
do_plot()
#> Error in `stat_density(aes(fill = after_stat(density)), geom = "raster", position =
#> "identity")`:
#> ! Problem while computing stat.
#> ℹ Error occurred in the 1st layer.
#> Caused by error in `setup_params()` at ggplot2/R/ggproto.r:182:16:
#> ! `stat_density()` must only have an x or y aesthetic.
```



<sup>Created on 2022-07-27 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by clauswilke** [comment]
@yutannihilation The example you found that breaks is an important use case I think. Fundamentally this highlights the core problem, which is that we don't explicitly distinguish between aesthetics given to the stat and to the geom. We may have to accept the confusing error message.

**Comment by yutannihilation** [comment]
Thanks. Yes, I'm almost giving up this pull request. Rather, my current concern is if `stat_bin()` and `stat_count()` might be also wrong. The below example won't work even if I remove "must only have an x or y" check, but I don't figure out if this should work like the example of `stat_density()` above or not...

``` r
ggplot(mtcars, aes(mpg, factor(cyl))) +
  stat_bin(aes(fill = after_stat(count)), geom = "raster", position = "identity")
```

**Comment by yutannihilation** [comment]
As this pull request seems impossible, I'm giving up this. Sorry that I didn't come up with the usage.

**Pull request closed without merging**
