### PR TITLE
add an "outside" argument to geom_rug() to allow for moving rug tasse…

### PR DESCRIPTION
**Pull request by njtierney**
…ls to outside the plot area

### CODE REVIEW

**Comment by thomasp85** [comment]
Can I get you to run `devtools::document()` so the documentation gets updated

**Comment by njtierney** [comment]
``` r
library(ggplot2)

# current behaviour with tassels inside figure area
ggplot(airquality,
       aes(x = Ozone,
           y = Solar.R)) + 
  geom_rug()
```



``` r

# move the tassels outside, remembering to turn off clipping
ggplot(airquality,
       aes(x = Ozone,
           y = Solar.R)) + 
  geom_rug(outside = TRUE) + 
  coord_cartesian(clip = "off")
```



``` r

# move the tassels to top right side, and expand margin
ggplot(airquality,
       aes(x = Ozone,
           y = Solar.R)) + 
  geom_rug(outside = TRUE,
           sides = "tr") + 
  coord_cartesian(clip = "off") +
  theme(plot.margin = margin(1,1,1,1, "cm"))
```



<sup>Created on 2019-01-19 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by njtierney** [comment]
Here's a reprex to demonstrate the behaviour:

``` r
library(ggplot2)

# current behaviour with tassels inside figure area
ggplot(airquality,
       aes(x = Ozone,
           y = Solar.R)) + 
  geom_rug()
```



``` r

# move the tassels outside, remembering to turn off clipping
ggplot(airquality,
       aes(x = Ozone,
           y = Solar.R)) + 
  geom_rug(outside = TRUE) + 
  coord_cartesian(clip = "off")
```



``` r

# move the tassels to top right side, and expand margin
ggplot(airquality,
       aes(x = Ozone,
           y = Solar.R)) + 
  geom_rug(outside = TRUE,
           sides = "tr") + 
  coord_cartesian(clip = "off") +
  theme(plot.margin = margin(1,1,1,1, "cm"))
```



<sup>Created on 2019-01-19 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by karawoo** [comment]
@njtierney If you're up for another PR I think it would be worth adding a test for this new behavior.

**Comment by njtierney** [comment]
@karawoo - great idea! I'll get cracking on that now. :)

**Pull request merged**
