### PR TITLE
revert hjust/vjust rotation for cases with mixed justification models

### PR DESCRIPTION
**Pull request by clauswilke**
See #2653 for details.

### CODE REVIEW

**Comment by clauswilke** [comment]
On further reflection, maybe I should just move the old piecewise rotation code into the `rotate_just()` function and be done with it for this release. We can try to tackle the problem more generally in a future update. Also, I think we need a visual regression test for x axis labels at an angle. That's the most common scenario where we need angles that deviate from 0, 90, 180, 270.

**Comment by hadley** [comment]
Yeah, I think it makes sense to roll back for now. We can think it through more for the next release.

**Comment by clauswilke** [comment]
Rollback done, and added visual test for rotated axis tick labels.

**Comment by karawoo** [comment]
```
## but it currently breaks things in certain cases
```

Knowing that we and/or others will inevitably revisit this again in the future, could we add a little information (like a link to #2653) to remind ourselves of what the problem was?

**Comment by clauswilke** [comment]
Done.

**Comment by hadley** [comment]
@clauswilke you can feel free to squash-merge once I've reviewed

**Pull request merged**
